/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.conexiones;
import Metodos.metodosSQLUsuario;
import static Metodos.metodosSQLUsuario.con;
import Modelo.Persona;
import Modelo.Usuario;
import Vista.BuscarUsuario;
import Vista.Login;
import java.awt.Color;
import java.awt.Image;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RojeruSan
 */
public class CRegistroUsuarios1 extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    conexiones con = new conexiones();
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelo;
    metodosSQLUsuario sql = new metodosSQLUsuario();

    public CRegistroUsuarios1() {
        initComponents();
        this.setLocationRelativeTo(this);
        setIconImage(getIconImage());
        listar();
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Images/autoicon.jpg"));

        return retValue;
    }

    void listar() {
        String sql = "SELECT * FROM usuarios";
        try {
            cn = con.Conectarse();
            st = cn.createStatement();
            rs = st.executeQuery(sql);
            Object[] usuario = new Object[6];
            modelo = (DefaultTableModel) jUsu.getModel();
            while (rs.next()) {
                usuario[0] = rs.getString("nombre");
                usuario[1] = rs.getString("apellido");
                usuario[2] = rs.getString("usuario");
                usuario[3] = rs.getString("password");
                usuario[4] = rs.getString("rango");
                usuario[5] = rs.getString("recuperarcodigo");

                modelo.addRow(usuario);

            }
            jUsu.setModel(modelo);
        } catch (Exception e) {
        }
    }

    void limpiartabla() {
        int filas = jUsu.getRowCount();
        for (int i = 0; i < filas; i++) {
            modelo.removeRow(0);

        }
    }

    void clear() {
        txtNombre.setText("");
        txtapellido.setText("");
        txtusuario.setText("");
        cboxrango.setSelectedItem("OPCIONES");
        txtrecuperar.setText("");
        txtPasword.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        lblapellido = new javax.swing.JLabel();
        lblpass = new javax.swing.JLabel();
        lblrango = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        txtPasword = new javax.swing.JPasswordField();
        cboxrango = new javax.swing.JComboBox<>();
        lblnombre1 = new javax.swing.JLabel();
        lblnombre2 = new javax.swing.JLabel();
        lblnombre3 = new javax.swing.JLabel();
        lblnombre4 = new javax.swing.JLabel();
        lblpass1 = new javax.swing.JLabel();
        lblnombre7 = new javax.swing.JLabel();
        txtrecuperar = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        lblminimizar = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jUsu = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnguardar = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        jcboxMostarPass = new javax.swing.JCheckBox();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(111, 174, 2), 5, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(656, 443));

        pnlMenu.setBackground(new java.awt.Color(0, 0, 0));
        pnlMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(111, 174, 2), 3, true));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/usuario.png"))); // NOI18N

        lblnombre.setFont(new java.awt.Font("Engravers MT", 1, 15)); // NOI18N
        lblnombre.setForeground(new java.awt.Color(111, 174, 2));
        lblnombre.setText("NOMBRE:");

        lblusuario.setFont(new java.awt.Font("Engravers MT", 1, 15)); // NOI18N
        lblusuario.setForeground(new java.awt.Color(111, 174, 2));
        lblusuario.setText("USUARIo:");

        lblapellido.setFont(new java.awt.Font("Engravers MT", 1, 15)); // NOI18N
        lblapellido.setForeground(new java.awt.Color(111, 174, 2));
        lblapellido.setText("APELLIDO:");

        lblpass.setFont(new java.awt.Font("Engravers MT", 1, 15)); // NOI18N
        lblpass.setForeground(new java.awt.Color(111, 174, 2));
        lblpass.setText("PASSWORD:");

        lblrango.setFont(new java.awt.Font("Engravers MT", 1, 15)); // NOI18N
        lblrango.setForeground(new java.awt.Color(111, 174, 2));
        lblrango.setText("RANGO:");

        txtusuario.setEditable(false);
        txtusuario.setBackground(new java.awt.Color(33, 33, 33));
        txtusuario.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtusuario.setForeground(new java.awt.Color(111, 174, 2));
        txtusuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        txtusuario.setEnabled(false);
        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });

        txtapellido.setBackground(new java.awt.Color(33, 33, 33));
        txtapellido.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtapellido.setForeground(new java.awt.Color(111, 174, 2));
        txtapellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        txtapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellidoActionPerformed(evt);
            }
        });
        txtapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtapellidoKeyReleased(evt);
            }
        });

        txtPasword.setBackground(new java.awt.Color(51, 51, 51));
        txtPasword.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtPasword.setForeground(new java.awt.Color(111, 174, 2));
        txtPasword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));

        cboxrango.setBackground(new java.awt.Color(51, 51, 51));
        cboxrango.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cboxrango.setForeground(new java.awt.Color(111, 174, 2));
        cboxrango.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OPCIONES", "ADMINISTRADOR", "USUARIO" }));
        cboxrango.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(111, 174, 2), 1, true));
        cboxrango.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblnombre1.setFont(new java.awt.Font("Engravers MT", 1, 15)); // NOI18N
        lblnombre1.setForeground(new java.awt.Color(111, 174, 2));
        lblnombre1.setText("*");

        lblnombre2.setFont(new java.awt.Font("Engravers MT", 1, 15)); // NOI18N
        lblnombre2.setForeground(new java.awt.Color(111, 174, 2));
        lblnombre2.setText("*");

        lblnombre3.setFont(new java.awt.Font("Engravers MT", 1, 15)); // NOI18N
        lblnombre3.setForeground(new java.awt.Color(111, 174, 2));
        lblnombre3.setText("*");

        lblnombre4.setFont(new java.awt.Font("Engravers MT", 1, 15)); // NOI18N
        lblnombre4.setForeground(new java.awt.Color(111, 174, 2));
        lblnombre4.setText("*");

        lblpass1.setFont(new java.awt.Font("Engravers MT", 1, 15)); // NOI18N
        lblpass1.setForeground(new java.awt.Color(111, 174, 2));
        lblpass1.setText("COD/RECUPERAR");

        lblnombre7.setFont(new java.awt.Font("Engravers MT", 1, 15)); // NOI18N
        lblnombre7.setForeground(new java.awt.Color(111, 174, 2));
        lblnombre7.setText("*");

        txtrecuperar.setBackground(new java.awt.Color(33, 33, 33));
        txtrecuperar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtrecuperar.setForeground(new java.awt.Color(111, 174, 2));
        txtrecuperar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        txtrecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrecuperarActionPerformed(evt);
            }
        });
        txtrecuperar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtrecuperarKeyReleased(evt);
            }
        });

        txtNombre.setBackground(new java.awt.Color(33, 33, 33));
        txtNombre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(111, 174, 2));
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        txtNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblnombre)
                    .addComponent(lblapellido)
                    .addComponent(lblusuario)
                    .addComponent(lblpass)
                    .addComponent(lblrango)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cboxrango, javax.swing.GroupLayout.Alignment.LEADING, 0, 159, Short.MAX_VALUE)
                                .addComponent(txtusuario, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtapellido, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPasword, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(txtNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblnombre1)
                            .addComponent(lblnombre2)
                            .addComponent(lblnombre3)
                            .addComponent(lblnombre4)))
                    .addComponent(lblpass1)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addComponent(txtrecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblnombre7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblnombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblnombre1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(lblapellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnombre2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblusuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnombre3))
                .addGap(18, 18, 18)
                .addComponent(lblpass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPasword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnombre4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblrango)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboxrango, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblpass1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombre7)
                    .addComponent(txtrecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        lblminimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Expand_Arrow_32px.png"))); // NOI18N
        lblminimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblminimizarMouseClicked(evt);
            }
        });

        btnCerrar.setBackground(new java.awt.Color(0, 0, 0));
        btnCerrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Delete_32px.png"))); // NOI18N
        btnCerrar.setAutoscrolls(true);
        btnCerrar.setBorder(null);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCerrar.setOpaque(true);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTROS/USUARIO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(111, 174, 2))); // NOI18N
        jPanel2.setOpaque(false);

        jUsu.setBackground(new java.awt.Color(111, 174, 2));
        jUsu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(111, 174, 2), 3, true));
        jUsu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jUsu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE", "APELLIDO", "USUARIO", "PASSWORD", "RANGO", "RECUPERARCODIGO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jUsu.setSelectionBackground(new java.awt.Color(102, 204, 0));
        jUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jUsuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jUsu);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setOpaque(false);

        btnguardar.setBackground(new java.awt.Color(0, 0, 0));
        btnguardar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(111, 174, 2));
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/guardar_doc.png"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(111, 174, 2), 2, true));
        btnguardar.setOpaque(false);
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnclear.setBackground(new java.awt.Color(51, 51, 51));
        btnclear.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnclear.setForeground(new java.awt.Color(111, 174, 2));
        btnclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/borrar.png"))); // NOI18N
        btnclear.setText("Limpiar");
        btnclear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(111, 174, 2), 2, true));
        btnclear.setOpaque(false);
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        btneliminar.setBackground(new java.awt.Color(0, 0, 0));
        btneliminar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btneliminar.setForeground(new java.awt.Color(111, 174, 2));
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eliminar_doc.png"))); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(111, 174, 2), 2, true));
        btneliminar.setOpaque(false);
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnbuscar.setBackground(new java.awt.Color(0, 0, 0));
        btnbuscar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnbuscar.setForeground(new java.awt.Color(111, 174, 2));
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buscar_doc.png"))); // NOI18N
        btnbuscar.setText("Buscar");
        btnbuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(111, 174, 2), 2, true));
        btnbuscar.setOpaque(false);
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnguardar, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jcboxMostarPass.setBackground(new java.awt.Color(0, 0, 0));
        jcboxMostarPass.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jcboxMostarPass.setForeground(new java.awt.Color(111, 174, 2));
        jcboxMostarPass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(111, 174, 2), 2, true));
        jcboxMostarPass.setLabel("Show Password");
        jcboxMostarPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboxMostarPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblminimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jcboxMostarPass, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblminimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jcboxMostarPass)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 928, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed

        this.dispose();

    }//GEN-LAST:event_btnCerrarActionPerformed

    private void lblminimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblminimizarMouseClicked
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_lblminimizarMouseClicked

    private void txtapellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidoKeyReleased
        //VALIDACIONES
        Character validar = evt.getKeyChar();
        //NO TENGAN LETRAS
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "¡Ingrese solo letras!", "MENSAJE DE ERROR", JOptionPane.ERROR_MESSAGE);
            txtapellido.setText("");
        }
    }//GEN-LAST:event_txtapellidoKeyReleased

    private void txtapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidoActionPerformed

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioActionPerformed

    private void txtrecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrecuperarActionPerformed

    }//GEN-LAST:event_txtrecuperarActionPerformed

    private void txtrecuperarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrecuperarKeyReleased
        //MENOR A 10 CARACTERES
        if (txtrecuperar.getText().length() == 11) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(rootPane, "¡Debe tener 10 letras!", "MENSAJE DE ERROR", JOptionPane.ERROR_MESSAGE);
            txtrecuperar.setText("");
        }
        //VALIDACIONES
        Character validar = evt.getKeyChar();
        //NO TENGAN NUMEROS
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "¡Ingrese solo letras!", "MENSAJE DE ERROR", JOptionPane.ERROR_MESSAGE);
            txtrecuperar.setText("");
        }

    }//GEN-LAST:event_txtrecuperarKeyReleased

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        //VALIDACIONES
        Character validar = evt.getKeyChar();
        //NO TENGAN NUMEROS
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "¡Ingrese solo letras!", "MENSAJE DE ERROR", JOptionPane.ERROR_MESSAGE);
            txtNombre.setText("");
        }
    }//GEN-LAST:event_txtNombreKeyReleased

    private void jUsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUsuMouseClicked
        // TODO add your handling code here:
//        txtPlaca.setEditable(false);
//        txtPlaca.setEnabled(false);
        int fila = jUsu.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "FIla no seleccionada");
        } else {
            txtNombre.setText(jUsu.getValueAt(fila, 0).toString());
            txtapellido.setText(jUsu.getValueAt(fila, 1).toString());
            txtusuario.setText(jUsu.getValueAt(fila, 2).toString());
            txtPasword.setText(jUsu.getValueAt(fila, 3).toString());
            cboxrango.setSelectedItem(jUsu.getValueAt(fila, 4).toString());
            txtrecuperar.setText(jUsu.getValueAt(fila, 5).toString());
        }
    }//GEN-LAST:event_jUsuMouseClicked

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnclearActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        int s = JOptionPane.showConfirmDialog(null, "Esta seguro de eliminar este registro", "Si/No", 0);
        if (s == 0) {
            int res = 0;
            int row = jUsu.getSelectedRow();
            int fila = jUsu.getSelectedColumnCount();
            if (fila < 1) {
                JOptionPane.showMessageDialog(null, "DEBE SELECCIONAR UN REGISTRO DE LA TABLA", "AVISO", JOptionPane.INFORMATION_MESSAGE);

            } else {
                res = sql.eliminarRegistro(jUsu.getValueAt(row, 2).toString());
                if (res >= 0) {
                    limpiartabla();
                    listar();
                    clear();
                }
            }
        }

    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        int s = JOptionPane.showConfirmDialog(null, "Esta seguro de modificar este usuario", "Si/No", 0);
        if (s == 0) {
            if (txtNombre.getText().isEmpty() || txtapellido.getText().isEmpty() || txtusuario.getText().isEmpty() || txtPasword.getText().isEmpty() || txtrecuperar.getText().isEmpty()) {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "*CAMPOS OBLIGATORIOS");
            } else {
                boolean estado;
                int rol;
                if (cboxrango.getSelectedItem().equals("ADMINISTRADOR")) {
                    rol = 1;
                    estado = true;
                } else {
                    rol = 2;
                    estado = true;
                }
                Usuario u = new Usuario(txtNombre.getText(), txtapellido.getText(), txtusuario.getText(), txtPasword.getText(), (String) cboxrango.getSelectedItem(), estado, rol, txtrecuperar.getText());
                int i = sql.actualizar(u);

                limpiartabla();
                listar();
                txtNombre.setText("");
                txtapellido.setText("");
                txtusuario.setText("");
                txtPasword.setText("");
                cboxrango.setSelectedItem("OPCIONES");
                txtrecuperar.setText("");

            }
        }

    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        BuscarUsuario b = new BuscarUsuario(this, true);
        b.setVisible(true);

        txtNombre.setText(b.getNombre());
        txtapellido.setText(b.getApellido());
        txtusuario.setText(b.getUsario());
        txtPasword.setText(b.getContra());
        txtrecuperar.setText(b.getCodrecuperacion());
        cboxrango.setSelectedItem(b.rango);

        txtusuario.setEditable(true);
        txtusuario.setEnabled(false);


    }//GEN-LAST:event_btnbuscarActionPerformed

    private void jcboxMostarPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboxMostarPassActionPerformed
        if (jcboxMostarPass.isSelected()) {
            txtPasword.setEchoChar((char) 0);
        } else {
            txtPasword.setEchoChar('*');
        }
    }//GEN-LAST:event_jcboxMostarPassActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JComboBox<String> cboxrango;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jUsu;
    private javax.swing.JCheckBox jcboxMostarPass;
    private javax.swing.JLabel lblapellido;
    private javax.swing.JLabel lblminimizar;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblnombre1;
    private javax.swing.JLabel lblnombre2;
    private javax.swing.JLabel lblnombre3;
    private javax.swing.JLabel lblnombre4;
    private javax.swing.JLabel lblnombre7;
    private javax.swing.JLabel lblpass;
    private javax.swing.JLabel lblpass1;
    private javax.swing.JLabel lblrango;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPasword;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtrecuperar;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
