/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Metodos.metodosSQLPersonas;
import com.itextpdf.text.DocumentException;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.util.*;
import java.text.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author MATUTE
 */
public class MenuPrincipal extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form MENUPRINCIPAL
     */
    String hora,minutos,segundos;
    Thread hilo;
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(this);
        setIconImage(getIconImage());
        lblfecha.setText(fecha());
        hilo=new Thread(this);
        hilo.start();
//        setVisible(true);
    }
    public void hora(){
        Calendar calendario=new GregorianCalendar();
        Date horario=new Date();
        calendario.setTime(horario);
        hora=calendario.get(Calendar.HOUR_OF_DAY)>9?""+calendario.get(Calendar.HOUR_OF_DAY):"0"+calendario.get(Calendar.HOUR_OF_DAY);
        minutos=calendario.get(Calendar.MINUTE)>9?""+calendario.get(Calendar.MINUTE):"0"+calendario.get(Calendar.MINUTE);
        segundos=calendario.get(Calendar.SECOND)>9?""+calendario.get(Calendar.SECOND):"0"+calendario.get(Calendar.SECOND);
    }
    public void run(){
        Thread current=Thread.currentThread();
//        while(current==hilo){
//            lblhora.setText(hora+":"+minutos+":"+segundos);
//        }
            for (int i = 1; i >0; i++) {
            if(i>0){
                hora();
                 lblhora.setText(hora+":"+minutos+":"+segundos);
            }
        }
    }
    public static String fecha(){
        Date fecha= new Date();
        SimpleDateFormat frmato=new SimpleDateFormat("dd/MM/YYYY");
        return frmato.format(fecha);
    }
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Images/autoicon.jpg"));

        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu3 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnsalir = new javax.swing.JButton();
        lblcodigo5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblfecha = new javax.swing.JLabel();
        lblhora = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        MenuBar = new javax.swing.JMenuBar();
        MOpciones = new javax.swing.JMenu();
        MCRUD = new javax.swing.JMenu();
        CRUDUsuarios = new javax.swing.JMenuItem();
        CRUDPersonas = new javax.swing.JMenuItem();
        CRUDPropietarios = new javax.swing.JMenuItem();
        CRUDEmpleados = new javax.swing.JMenuItem();
        CRUDVehiculos = new javax.swing.JMenuItem();
        MReportes = new javax.swing.JMenu();
        Reportes = new javax.swing.JMenu();
        ReportesUsuarios = new javax.swing.JMenuItem();
        ReportesPersonas = new javax.swing.JMenuItem();
        ReportesPropietarios = new javax.swing.JMenuItem();
        ReportesEmpleados = new javax.swing.JMenuItem();
        ReportesVehiculos = new javax.swing.JMenuItem();
        ReportesEstacionamiento = new javax.swing.JMenuItem();
        ReportesParking = new javax.swing.JMenuItem();
        Masignar = new javax.swing.JMenu();
        asignavehiculos = new javax.swing.JMenu();
        AsignaPropietarios = new javax.swing.JMenuItem();
        AsingaEstacionamiento = new javax.swing.JMenuItem();
        MenuRetirar = new javax.swing.JMenu();
        RetirarVehiculo = new javax.swing.JMenuItem();
        MenuRetirar1 = new javax.swing.JMenu();
        RetirarVehiculo1 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Menu Principal");
        setIconImage(getIconImage());
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(111, 174, 2), 4, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LOGOTIPO1.0.jpeg"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(111, 174, 2), 4, true));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 200, 170));

        btnsalir.setBackground(new java.awt.Color(0, 0, 0));
        btnsalir.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        btnsalir.setForeground(new java.awt.Color(111, 174, 2));
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Sign_Out_32px.png"))); // NOI18N
        btnsalir.setText("SALIR  ");
        btnsalir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(111, 174, 2), 1, true));
        btnsalir.setOpaque(false);
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 340, 119, -1));

        lblcodigo5.setFont(new java.awt.Font("Engravers MT", 3, 36)); // NOI18N
        lblcodigo5.setForeground(new java.awt.Color(111, 174, 2));
        lblcodigo5.setText("PARKING PROJECT");
        jPanel2.add(lblcodigo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 490, 50));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setOpaque(false);

        jLabel8.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(111, 174, 2));
        jLabel8.setText("FECHA:");

        jLabel7.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(111, 174, 2));
        jLabel7.setText("HORA:");

        lblfecha.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblfecha.setForeground(new java.awt.Color(153, 0, 0));
        lblfecha.setText("DD/MM/AAAA");

        lblhora.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblhora.setForeground(new java.awt.Color(153, 0, 0));
        lblhora.setText("00:00:00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblhora, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblhora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 240, 90));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(111, 174, 2));
        jTextArea1.setRows(5);
        jTextArea1.setText("\n-JOSE DANIEL MURILLO MAYANCELA\n-BRAYAN ALEXIS IDROBO CELI\n-PEDRO SEBASTIAN CABRERA LOJANO\n");
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "AUTORES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(111, 174, 2))); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 310, 130));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea2.setColumns(20);
        jTextArea2.setForeground(new java.awt.Color(111, 174, 2));
        jTextArea2.setRows(5);
        jTextArea2.setText("EMAIL... \n-pedro.cabrera.est@tecazuay.edu.ec\n-jose.murillo.est@tecazuay.edu.ec\n-brayan.idrobo.est@tecazuay.edu.ec\n\nTELEFONO...\n- +593 988787152\n\nDIRECCION POSTAL\nAZUAY 010110\n\n");
        jTextArea2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONTACTOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(111, 174, 2))); // NOI18N
        jScrollPane2.setViewportView(jTextArea2);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 310, 250));

        MenuBar.setBackground(new java.awt.Color(0, 0, 0));
        MenuBar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(111, 174, 2), 4, true));

        MOpciones.setBackground(new java.awt.Color(0, 0, 0));
        MOpciones.setForeground(new java.awt.Color(111, 174, 2));
        MOpciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Menu_32px.png"))); // NOI18N
        MOpciones.setText("Opciones");
        MOpciones.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N

        MCRUD.setBackground(new java.awt.Color(0, 0, 0));
        MCRUD.setForeground(new java.awt.Color(111, 174, 2));
        MCRUD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/anadir.png"))); // NOI18N
        MCRUD.setText("CRUD");
        MCRUD.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N

        CRUDUsuarios.setBackground(new java.awt.Color(0, 0, 0));
        CRUDUsuarios.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        CRUDUsuarios.setForeground(new java.awt.Color(111, 174, 2));
        CRUDUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/agregar-usuario.png"))); // NOI18N
        CRUDUsuarios.setText("USUARIOS");
        CRUDUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CRUDUsuariosActionPerformed(evt);
            }
        });
        MCRUD.add(CRUDUsuarios);

        CRUDPersonas.setBackground(new java.awt.Color(0, 0, 0));
        CRUDPersonas.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        CRUDPersonas.setForeground(new java.awt.Color(111, 174, 2));
        CRUDPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/trabajo-en-equipo.png"))); // NOI18N
        CRUDPersonas.setText("Personas");
        CRUDPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CRUDPersonasActionPerformed(evt);
            }
        });
        MCRUD.add(CRUDPersonas);

        CRUDPropietarios.setBackground(new java.awt.Color(0, 0, 0));
        CRUDPropietarios.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        CRUDPropietarios.setForeground(new java.awt.Color(111, 174, 2));
        CRUDPropietarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/propietario.png"))); // NOI18N
        CRUDPropietarios.setText("Propietarios");
        CRUDPropietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CRUDPropietariosActionPerformed(evt);
            }
        });
        MCRUD.add(CRUDPropietarios);

        CRUDEmpleados.setBackground(new java.awt.Color(0, 0, 0));
        CRUDEmpleados.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        CRUDEmpleados.setForeground(new java.awt.Color(111, 174, 2));
        CRUDEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gerente.png"))); // NOI18N
        CRUDEmpleados.setText("Empleados");
        CRUDEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CRUDEmpleadosActionPerformed(evt);
            }
        });
        MCRUD.add(CRUDEmpleados);

        CRUDVehiculos.setBackground(new java.awt.Color(0, 0, 0));
        CRUDVehiculos.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        CRUDVehiculos.setForeground(new java.awt.Color(111, 174, 2));
        CRUDVehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coche.png"))); // NOI18N
        CRUDVehiculos.setText("Vehiculos");
        CRUDVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CRUDVehiculosActionPerformed(evt);
            }
        });
        MCRUD.add(CRUDVehiculos);

        MOpciones.add(MCRUD);

        MenuBar.add(MOpciones);

        MReportes.setBackground(new java.awt.Color(0, 0, 0));
        MReportes.setForeground(new java.awt.Color(111, 174, 2));
        MReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Bar_Chart_32px.png"))); // NOI18N
        MReportes.setText("Reportes");
        MReportes.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N

        Reportes.setBackground(new java.awt.Color(0, 0, 0));
        Reportes.setForeground(new java.awt.Color(111, 174, 2));
        Reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reporte.png"))); // NOI18N
        Reportes.setText("Reportes");
        Reportes.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N

        ReportesUsuarios.setBackground(new java.awt.Color(0, 0, 0));
        ReportesUsuarios.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        ReportesUsuarios.setForeground(new java.awt.Color(111, 174, 2));
        ReportesUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/agregar-usuario.png"))); // NOI18N
        ReportesUsuarios.setText("USUARIOS");
        ReportesUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportesUsuariosActionPerformed(evt);
            }
        });
        Reportes.add(ReportesUsuarios);

        ReportesPersonas.setBackground(new java.awt.Color(0, 0, 0));
        ReportesPersonas.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        ReportesPersonas.setForeground(new java.awt.Color(111, 174, 2));
        ReportesPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/trabajo-en-equipo.png"))); // NOI18N
        ReportesPersonas.setText("PERSONAS");
        ReportesPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportesPersonasActionPerformed(evt);
            }
        });
        Reportes.add(ReportesPersonas);

        ReportesPropietarios.setBackground(new java.awt.Color(0, 0, 0));
        ReportesPropietarios.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        ReportesPropietarios.setForeground(new java.awt.Color(111, 174, 2));
        ReportesPropietarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/propietario.png"))); // NOI18N
        ReportesPropietarios.setText("Propietarios");
        ReportesPropietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportesPropietariosActionPerformed(evt);
            }
        });
        Reportes.add(ReportesPropietarios);

        ReportesEmpleados.setBackground(new java.awt.Color(0, 0, 0));
        ReportesEmpleados.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        ReportesEmpleados.setForeground(new java.awt.Color(111, 174, 2));
        ReportesEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gerente.png"))); // NOI18N
        ReportesEmpleados.setText("Empleados");
        ReportesEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportesEmpleadosActionPerformed(evt);
            }
        });
        Reportes.add(ReportesEmpleados);

        ReportesVehiculos.setBackground(new java.awt.Color(0, 0, 0));
        ReportesVehiculos.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        ReportesVehiculos.setForeground(new java.awt.Color(111, 174, 2));
        ReportesVehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coche.png"))); // NOI18N
        ReportesVehiculos.setText("Vehiculos");
        ReportesVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportesVehiculosActionPerformed(evt);
            }
        });
        Reportes.add(ReportesVehiculos);

        ReportesEstacionamiento.setBackground(new java.awt.Color(0, 0, 0));
        ReportesEstacionamiento.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        ReportesEstacionamiento.setForeground(new java.awt.Color(111, 174, 2));
        ReportesEstacionamiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/estacionamiento.png"))); // NOI18N
        ReportesEstacionamiento.setText("Estacionamiento");
        ReportesEstacionamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportesEstacionamientoActionPerformed(evt);
            }
        });
        Reportes.add(ReportesEstacionamiento);

        ReportesParking.setBackground(new java.awt.Color(0, 0, 0));
        ReportesParking.setFont(new java.awt.Font("Engravers MT", 0, 12)); // NOI18N
        ReportesParking.setForeground(new java.awt.Color(111, 174, 2));
        ReportesParking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/REPORTEPARKING.png"))); // NOI18N
        ReportesParking.setText("PARKING");
        ReportesParking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportesParkingActionPerformed(evt);
            }
        });
        Reportes.add(ReportesParking);

        MReportes.add(Reportes);

        MenuBar.add(MReportes);

        Masignar.setBackground(new java.awt.Color(0, 0, 0));
        Masignar.setForeground(new java.awt.Color(111, 174, 2));
        Masignar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Keyboard_32px.png"))); // NOI18N
        Masignar.setText("ASIGNAR");
        Masignar.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N

        asignavehiculos.setBackground(new java.awt.Color(0, 0, 0));
        asignavehiculos.setForeground(new java.awt.Color(111, 174, 2));
        asignavehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coche.png"))); // NOI18N
        asignavehiculos.setText("vehiculos");
        asignavehiculos.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N

        AsignaPropietarios.setBackground(new java.awt.Color(0, 0, 0));
        AsignaPropietarios.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        AsignaPropietarios.setForeground(new java.awt.Color(111, 174, 2));
        AsignaPropietarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/propietario.png"))); // NOI18N
        AsignaPropietarios.setText("Propietarios");
        AsignaPropietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsignaPropietariosActionPerformed(evt);
            }
        });
        asignavehiculos.add(AsignaPropietarios);

        AsingaEstacionamiento.setBackground(new java.awt.Color(0, 0, 0));
        AsingaEstacionamiento.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        AsingaEstacionamiento.setForeground(new java.awt.Color(111, 174, 2));
        AsingaEstacionamiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/estacionamiento.png"))); // NOI18N
        AsingaEstacionamiento.setText("Estacionamiento");
        AsingaEstacionamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsingaEstacionamientoActionPerformed(evt);
            }
        });
        asignavehiculos.add(AsingaEstacionamiento);

        Masignar.add(asignavehiculos);

        MenuBar.add(Masignar);

        MenuRetirar.setBackground(new java.awt.Color(0, 0, 0));
        MenuRetirar.setForeground(new java.awt.Color(111, 174, 2));
        MenuRetirar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Mouse_32px.png"))); // NOI18N
        MenuRetirar.setText("Retirar");
        MenuRetirar.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N

        RetirarVehiculo.setBackground(new java.awt.Color(0, 0, 0));
        RetirarVehiculo.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        RetirarVehiculo.setForeground(new java.awt.Color(111, 174, 2));
        RetirarVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/estacionamiento.png"))); // NOI18N
        RetirarVehiculo.setText("Vehiculo");
        RetirarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetirarVehiculoActionPerformed(evt);
            }
        });
        MenuRetirar.add(RetirarVehiculo);

        MenuBar.add(MenuRetirar);

        MenuRetirar1.setBackground(new java.awt.Color(0, 0, 0));
        MenuRetirar1.setForeground(new java.awt.Color(111, 174, 2));
        MenuRetirar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/REPORTEPARKING.png"))); // NOI18N
        MenuRetirar1.setText("IMPRIMIR");
        MenuRetirar1.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N

        RetirarVehiculo1.setBackground(new java.awt.Color(0, 0, 0));
        RetirarVehiculo1.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        RetirarVehiculo1.setForeground(new java.awt.Color(111, 174, 2));
        RetirarVehiculo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/estacionamiento.png"))); // NOI18N
        RetirarVehiculo1.setText("iNFORME semanal");
        RetirarVehiculo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetirarVehiculo1ActionPerformed(evt);
            }
        });
        MenuRetirar1.add(RetirarVehiculo1);

        MenuBar.add(MenuRetirar1);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 999, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CRUDPropietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CRUDPropietariosActionPerformed
        RegistroPropietarios registers = new RegistroPropietarios();
        registers.setVisible(true);


    }//GEN-LAST:event_CRUDPropietariosActionPerformed

    private void CRUDVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CRUDVehiculosActionPerformed
        RegistroVehiculos register = new RegistroVehiculos();
        register.setVisible(true);
    }//GEN-LAST:event_CRUDVehiculosActionPerformed

    private void ReportesVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportesVehiculosActionPerformed
        ReporteVehiculo busca = new ReporteVehiculo(this, true);
        busca.setVisible(true);
    }//GEN-LAST:event_ReportesVehiculosActionPerformed

    private void ReportesPropietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportesPropietariosActionPerformed
        ReportePropietario busca = new ReportePropietario(this, true);
        busca.setVisible(true);
    }//GEN-LAST:event_ReportesPropietariosActionPerformed

    private void CRUDPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CRUDPersonasActionPerformed
        RegistroPersonas register = new RegistroPersonas();
        register.setVisible(true);

    }//GEN-LAST:event_CRUDPersonasActionPerformed

    private void CRUDEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CRUDEmpleadosActionPerformed
        RegistroEmpleados register = new RegistroEmpleados();
        register.setVisible(true);

    }//GEN-LAST:event_CRUDEmpleadosActionPerformed

    private void ReportesEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportesEmpleadosActionPerformed
        ReporteEmpleados report = new ReporteEmpleados(this, true);
        report.setVisible(true);
    }//GEN-LAST:event_ReportesEmpleadosActionPerformed

    private void ReportesPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportesPersonasActionPerformed
        ReportePersonas busca = new ReportePersonas(this, true);
        busca.setVisible(true);
    }//GEN-LAST:event_ReportesPersonasActionPerformed

    private void RetirarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetirarVehiculoActionPerformed
        RetirarVehiculo retiro = new RetirarVehiculo();
        retiro.setVisible(true);

    }//GEN-LAST:event_RetirarVehiculoActionPerformed

    private void ReportesEstacionamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportesEstacionamientoActionPerformed
        ReporteEstacionamiento esta = new ReporteEstacionamiento(this, true);
        esta.setVisible(true);
    }//GEN-LAST:event_ReportesEstacionamientoActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        getToolkit().beep();
        int opcion = JOptionPane.showConfirmDialog(null, "Desea cerrar sesión?", "Aviso", JOptionPane.YES_NO_OPTION);

        if (opcion == 0) { //The ISSUE is here

            Login log = new Login();
            log.setVisible(true);
            this.dispose();
        } else {

        }
    }//GEN-LAST:event_btnsalirActionPerformed

    private void CRUDUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CRUDUsuariosActionPerformed
        CRegistroUsuarios1 par = new CRegistroUsuarios1();
        par.setVisible(true);
    }//GEN-LAST:event_CRUDUsuariosActionPerformed

    private void ReportesUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportesUsuariosActionPerformed
      ReporteUsuario busca = new ReporteUsuario(this, true);
        busca.setVisible(true);
    }//GEN-LAST:event_ReportesUsuariosActionPerformed

    private void AsignaPropietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsignaPropietariosActionPerformed
        propetariovehiculos s = new propetariovehiculos(this, true);
        s.setVisible(true);
    }//GEN-LAST:event_AsignaPropietariosActionPerformed

    private void AsingaEstacionamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsingaEstacionamientoActionPerformed
        RegistroEntradaEstacionamiento busca = new RegistroEntradaEstacionamiento(this, true);
        busca.setVisible(true);
    }//GEN-LAST:event_AsingaEstacionamientoActionPerformed

    private void ReportesParkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportesParkingActionPerformed
        ReporteParking par = new ReporteParking(this, true);
        par.setVisible(true);
    }//GEN-LAST:event_ReportesParkingActionPerformed

    private void RetirarVehiculo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetirarVehiculo1ActionPerformed
        int s = JOptionPane.showConfirmDialog(null, "Esta seguro de imprimir?", "CONFIRMACION", 0);
        if (s == 0) {
            metodosSQLPersonas metodos=new metodosSQLPersonas();
            try {
                metodos.imprimirDOC();
            } catch (DocumentException | IOException ex) {
                Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_RetirarVehiculo1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JMenuItem AsignaPropietarios;
    public static javax.swing.JMenuItem AsingaEstacionamiento;
    public static javax.swing.JMenuItem CRUDEmpleados;
    private javax.swing.JMenuItem CRUDPersonas;
    public static javax.swing.JMenuItem CRUDPropietarios;
    public static javax.swing.JMenuItem CRUDUsuarios;
    public static javax.swing.JMenuItem CRUDVehiculos;
    public static javax.swing.JMenu MCRUD;
    public static javax.swing.JMenu MOpciones;
    public static javax.swing.JMenu MReportes;
    public static javax.swing.JMenu Masignar;
    public static javax.swing.JMenuBar MenuBar;
    public static javax.swing.JMenu MenuRetirar;
    public static javax.swing.JMenu MenuRetirar1;
    public static javax.swing.JMenu Reportes;
    public static javax.swing.JMenuItem ReportesEmpleados;
    public static javax.swing.JMenuItem ReportesEstacionamiento;
    public static javax.swing.JMenuItem ReportesParking;
    public static javax.swing.JMenuItem ReportesPersonas;
    public static javax.swing.JMenuItem ReportesPropietarios;
    public static javax.swing.JMenuItem ReportesUsuarios;
    public static javax.swing.JMenuItem ReportesVehiculos;
    public static javax.swing.JMenuItem RetirarVehiculo;
    public static javax.swing.JMenuItem RetirarVehiculo1;
    public static javax.swing.JMenu asignavehiculos;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lblcodigo5;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lblhora;
    // End of variables declaration//GEN-END:variables

}
