/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Metodos.MetodoSQLEstacionamiento;
import Metodos.MetodoSQLVehiculos;
import Metodos.metodosSQLPropietarios;
import static Metodos.metodosSQLUsuario.con;
import static Metodos.metodosSQLUsuario.sentencia_preparada;
import Modelo.Empleados;
import Modelo.Estacionamiento;
import Modelo.Propetariovehiculo;
import Modelo.Propietario;
import Vista.MenuPrincipal;
import static Vista.RegistroPropietarios.txtapellido;
import static Vista.RegistroPropietarios.txtnombre;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.sql.Time;
import java.time.LocalTime;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class propetariovehiculos extends javax.swing.JDialog {

    /**
     * Creates new form mBuscarPersonas
     */
    metodosSQLPropietarios sq = new metodosSQLPropietarios();
    MetodoSQLEstacionamiento sql2 = new MetodoSQLEstacionamiento();
    MetodoSQLVehiculos sql22 = new MetodoSQLVehiculos();
    private PreparedStatement PS;
    private ResultSet rst;

    public propetariovehiculos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        sql22.mostrarJ(CBPlaca);    
        sq.mostrarJ(CBDocu);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        tablap = new javax.swing.JPanel();
        btnconsultar1 = new javax.swing.JButton();
        lblcodigo = new javax.swing.JLabel();
        CBDocu = new javax.swing.JComboBox<>();
        lblcodigo1 = new javax.swing.JLabel();
        lblcodigo2 = new javax.swing.JLabel();
        Date = new com.toedter.calendar.JDateChooser();
        btnconsultar2 = new javax.swing.JButton();
        CBPlaca = new javax.swing.JComboBox<>();
        lblcodigo3 = new javax.swing.JLabel();
        lblcodigo4 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        javax.swing.JButton btnbuscar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(111, 174, 2), 4, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(111, 174, 2));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Home_32px.png"))); // NOI18N
        btnSalir.setText("REGRESAR");
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.setContentAreaFilled(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 160, 43));

        tablap.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTRO DE ENTRADA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18), new java.awt.Color(111, 174, 2))); // NOI18N
        tablap.setOpaque(false);

        btnconsultar1.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        btnconsultar1.setForeground(new java.awt.Color(111, 174, 2));
        btnconsultar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/estacionamiento.png"))); // NOI18N
        btnconsultar1.setText("LIMPIAR");
        btnconsultar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnconsultar1.setContentAreaFilled(false);
        btnconsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultar1ActionPerformed(evt);
            }
        });

        lblcodigo.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblcodigo.setForeground(new java.awt.Color(111, 174, 2));
        lblcodigo.setText("FECHA:");

        CBDocu.setBackground(new java.awt.Color(51, 51, 51));
        CBDocu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CBDocu.setForeground(new java.awt.Color(111, 174, 2));
        CBDocu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        CBDocu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CBDocu.setOpaque(false);
        CBDocu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBDocuActionPerformed(evt);
            }
        });

        lblcodigo1.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblcodigo1.setForeground(new java.awt.Color(111, 174, 2));
        lblcodigo1.setText("DOCUMENTO  PROPIETARIO:");

        lblcodigo2.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblcodigo2.setForeground(new java.awt.Color(111, 174, 2));
        lblcodigo2.setText("PLACA");

        Date.setBackground(new java.awt.Color(0, 0, 0));
        Date.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(111, 174, 2), 3, true));
        Date.setForeground(new java.awt.Color(111, 174, 2));
        Date.setDateFormatString("yyyy-MM-dd");
        Date.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        btnconsultar2.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        btnconsultar2.setForeground(new java.awt.Color(111, 174, 2));
        btnconsultar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/estacionamiento.png"))); // NOI18N
        btnconsultar2.setText("REGISTRAR");
        btnconsultar2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnconsultar2.setContentAreaFilled(false);
        btnconsultar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultar2ActionPerformed(evt);
            }
        });

        CBPlaca.setBackground(new java.awt.Color(51, 51, 51));
        CBPlaca.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CBPlaca.setForeground(new java.awt.Color(111, 174, 2));
        CBPlaca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        CBPlaca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CBPlaca.setOpaque(false);

        lblcodigo3.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblcodigo3.setForeground(new java.awt.Color(111, 174, 2));
        lblcodigo3.setText("NOMBRE:");

        lblcodigo4.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblcodigo4.setForeground(new java.awt.Color(111, 174, 2));
        lblcodigo4.setText("APELLIDO:");

        txtNom.setEditable(false);
        txtNom.setBackground(new java.awt.Color(51, 51, 51));
        txtNom.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtNom.setForeground(new java.awt.Color(111, 174, 2));
        txtNom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        txtNom.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNom.setEnabled(false);

        txtApellido.setEditable(false);
        txtApellido.setBackground(new java.awt.Color(51, 51, 51));
        txtApellido.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(111, 174, 2));
        txtApellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        txtApellido.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtApellido.setEnabled(false);

        btnbuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnbuscar.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        btnbuscar.setForeground(new java.awt.Color(111, 174, 2));
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/trabajo-en-equipo.png"))); // NOI18N
        btnbuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnbuscar.setContentAreaFilled(false);
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tablapLayout = new javax.swing.GroupLayout(tablap);
        tablap.setLayout(tablapLayout);
        tablapLayout.setHorizontalGroup(
            tablapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablapLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(tablapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcodigo1)
                    .addGroup(tablapLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblcodigo2))
                    .addGroup(tablapLayout.createSequentialGroup()
                        .addGroup(tablapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tablapLayout.createSequentialGroup()
                                .addGroup(tablapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblcodigo4)
                                    .addComponent(lblcodigo3))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablapLayout.createSequentialGroup()
                                .addComponent(lblcodigo)
                                .addGap(48, 48, 48)))
                        .addGroup(tablapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tablapLayout.createSequentialGroup()
                                .addComponent(CBDocu, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(tablapLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnconsultar2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnconsultar1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tablapLayout.setVerticalGroup(
            tablapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablapLayout.createSequentialGroup()
                .addComponent(lblcodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tablapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CBDocu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar))
                .addGap(43, 43, 43)
                .addGroup(tablapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(tablapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(tablapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcodigo3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(tablapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcodigo4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(tablapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnconsultar1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnconsultar2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(tablap, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 440, 450));

        btnCerrar.setBackground(new java.awt.Color(0, 0, 0));
        btnCerrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Delete_32px.png"))); // NOI18N
        btnCerrar.setAutoscrolls(true);
        btnCerrar.setBorder(null);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCerrar.setOpaque(true);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 40, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/registros.gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 240, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnconsultar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultar2ActionPerformed
        // TODO add your handling code here:

        int s = JOptionPane.showConfirmDialog(null, "Desea asignar el vehiculo a esta persona", "Si/No", 0);
        if (s == 0) {
            if (CBPlaca.getSelectedIndex() == 0 || CBDocu.getSelectedIndex()==0) {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "*CAMPOS OBLIGATORIOS", "INFORMATIVO", JOptionPane.INFORMATION_MESSAGE);
            } else {

                // String num_area, String nro_Placa, Date fecha, Date hora_entrada)
                Propetariovehiculo pro = new Propetariovehiculo((String) CBDocu.getSelectedItem(), (String) CBPlaca.getSelectedItem());
                int i = sq.guardarPro3(pro);
                if (i > 0) {
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(this, "VEHICULO ASIGNADO  CON EXITO", "INFORMATIVO", JOptionPane.INFORMATION_MESSAGE);
                    clear();
                } else {
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(this, "NO SE PUDO ASIGNAR", "ERROR", JOptionPane.ERROR_MESSAGE);

                }

            }
        }
    }//GEN-LAST:event_btnconsultar2ActionPerformed

    private void btnconsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultar1ActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnconsultar1ActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        
           Cargar();
        


    }//GEN-LAST:event_btnbuscarActionPerformed

    private void CBDocuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBDocuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBDocuActionPerformed
    public void clear() {
        
        CBPlaca.setSelectedItem("Seleccione");
        CBDocu.setSelectedItem("Seleccione");
        Date.setDate(null);
        txtNom.setText("");
        txtApellido.setText("");
    }

    public void Cargar(){
        Connection conexion = null;
        
        String cargar = ("SELECT* FROM personas WHERE documento= '"+this.CBDocu.getSelectedItem()+"' ");
        try{
            conexion = con.Conectarse();
            sentencia_preparada = conexion.prepareStatement(cargar);
            rst = sentencia_preparada.executeQuery();
            rst.next();
            this.txtNom.setText(rst.getString("nombre"));
            this.txtApellido.setText(rst.getString("apellido"));
            
        }catch(Exception e){
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBDocu;
    private javax.swing.JComboBox<String> CBPlaca;
    private com.toedter.calendar.JDateChooser Date;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnconsultar1;
    private javax.swing.JButton btnconsultar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JLabel lblcodigo1;
    private javax.swing.JLabel lblcodigo2;
    private javax.swing.JLabel lblcodigo3;
    private javax.swing.JLabel lblcodigo4;
    private javax.swing.JPanel tablap;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtNom;
    // End of variables declaration//GEN-END:variables
}
