/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.conexiones;
import Metodos.metodosSQLEmpleado;

import Modelo.Empleados;

import java.awt.Image;
import java.awt.Toolkit;

import java.sql.Connection;
import java.sql.PreparedStatement;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class RegistroEmpleados extends javax.swing.JFrame {

    conexiones con = new conexiones();
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelo;
    int ng;
    String gener;

    public void setNg(int ng) {
        this.ng = ng;
    }

    /**
     * Creates new form RegistroPersonas
     */
    public RegistroEmpleados() {
        initComponents();
        this.setLocationRelativeTo(null);
        listar();
    }
//VARIABLES
    private PreparedStatement PS;

    private ResultSet rst;

    public void buscaDato(String parametro) {
        String sql;

        sql = "SELECT * FROM personas WHERE documento='" + parametro + "'";

        try {

            PS = con.Conectarse().prepareStatement(sql);
            rst = PS.executeQuery();
            Object[] fila = new Object[6];
            while (rst.next()) {
                fila[0] = rst.getString("tipo_documento");
                fila[1] = rst.getString("documento");
                fila[2] = rst.getString("nombre");
                fila[3] = rst.getString("apellido");
                fila[4] = rst.getString("genero");
                fila[5] = rst.getDate("fecha_nacimiento");

            }

            if (parametro.equals(fila[1])) {
                Toolkit.getDefaultToolkit().beep();

                txtnombre.setText(fila[2].toString());
                txtapellido.setText(fila[3].toString());

                btnregistrar.setEnabled(true);
                txtSueldo.setEnabled(true);
                txtSueldo.setEditable(true);
                CBRol.setEnabled(true);
                txtdoc.setEnabled(false);
                txtdoc.setEditable(false);
            } else {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null, "NO SE ENCONTRO A UNA PERSONA REGISTRADA CON ESE DOCUMENTO", "ERROR", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "ERROR AL CONSULTAR EL REGISTRO", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Images/autoicon.jpg"));

        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblminimizar = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        tablap = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtRegistro1 = new javax.swing.JTable();
        tablap1 = new javax.swing.JPanel();
        lblcodigo6 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        lblcodigo8 = new javax.swing.JLabel();
        txtSueldo = new javax.swing.JTextField();
        lblcodigo7 = new javax.swing.JLabel();
        CBRol = new javax.swing.JComboBox<>();
        panelbotones = new javax.swing.JPanel();
        btnregistrar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnconsultar1 = new javax.swing.JButton();
        IngresoDatospanel = new javax.swing.JPanel();
        txtdoc = new javax.swing.JTextField();
        lblcodigo1 = new javax.swing.JLabel();
        lblcodigo2 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        lblcodigo3 = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnbuscar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(111, 174, 2), 5, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblminimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Expand_Arrow_32px.png"))); // NOI18N
        lblminimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblminimizarMouseClicked(evt);
            }
        });
        jPanel1.add(lblminimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 20, 40, 30));

        btnCerrar.setBackground(new java.awt.Color(0, 0, 0));
        btnCerrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Delete_32px.png"))); // NOI18N
        btnCerrar.setAutoscrolls(true);
        btnCerrar.setBorder(null);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCerrar.setOpaque(true);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 20, -1, -1));

        tablap.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTROS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18), new java.awt.Color(111, 174, 2))); // NOI18N
        tablap.setOpaque(false);

        jtRegistro1.setBackground(new java.awt.Color(111, 174, 2));
        jtRegistro1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(111, 174, 2), 3, true));
        jtRegistro1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jtRegistro1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DOCUMENTO", "NOMBRE", "APELLIDO", "SUELDO", "ROL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtRegistro1.setSelectionBackground(new java.awt.Color(102, 204, 0));
        jtRegistro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtRegistro1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtRegistro1);

        javax.swing.GroupLayout tablapLayout = new javax.swing.GroupLayout(tablap);
        tablap.setLayout(tablapLayout);
        tablapLayout.setHorizontalGroup(
            tablapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addContainerGap())
        );
        tablapLayout.setVerticalGroup(
            tablapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablapLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jPanel1.add(tablap, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, 550, 220));

        tablap1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EMPLEADO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18), new java.awt.Color(111, 174, 2))); // NOI18N
        tablap1.setOpaque(false);

        lblcodigo6.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblcodigo6.setForeground(new java.awt.Color(111, 174, 2));
        lblcodigo6.setText("ID:");

        txtid.setEditable(false);
        txtid.setBackground(new java.awt.Color(51, 51, 51));
        txtid.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtid.setForeground(new java.awt.Color(111, 174, 2));
        txtid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        txtid.setEnabled(false);
        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtidKeyReleased(evt);
            }
        });

        lblcodigo8.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblcodigo8.setForeground(new java.awt.Color(111, 174, 2));
        lblcodigo8.setText("Sueldo:");

        txtSueldo.setEditable(false);
        txtSueldo.setBackground(new java.awt.Color(51, 51, 51));
        txtSueldo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtSueldo.setForeground(new java.awt.Color(111, 174, 2));
        txtSueldo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        txtSueldo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtSueldo.setEnabled(false);
        txtSueldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSueldoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSueldoKeyTyped(evt);
            }
        });

        lblcodigo7.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblcodigo7.setForeground(new java.awt.Color(111, 174, 2));
        lblcodigo7.setText("ROL:");

        CBRol.setBackground(new java.awt.Color(51, 51, 51));
        CBRol.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CBRol.setForeground(new java.awt.Color(111, 174, 2));
        CBRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Contador", "Guardia", "Limpieza", "Gerente General", " " }));
        CBRol.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CBRol.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CBRol.setEnabled(false);
        CBRol.setOpaque(false);
        CBRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBRolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tablap1Layout = new javax.swing.GroupLayout(tablap1);
        tablap1.setLayout(tablap1Layout);
        tablap1Layout.setHorizontalGroup(
            tablap1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablap1Layout.createSequentialGroup()
                .addGroup(tablap1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tablap1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(tablap1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblcodigo8)
                            .addComponent(lblcodigo6)
                            .addComponent(lblcodigo7)))
                    .addGroup(tablap1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(CBRol, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(tablap1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tablap1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tablap1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(txtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        tablap1Layout.setVerticalGroup(
            tablap1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablap1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblcodigo6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblcodigo8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(lblcodigo7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CBRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1.add(tablap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 410, 290));

        panelbotones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bradley Hand ITC", 1, 14), new java.awt.Color(111, 174, 2))); // NOI18N
        panelbotones.setOpaque(false);

        btnregistrar.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        btnregistrar.setForeground(new java.awt.Color(111, 174, 2));
        btnregistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nuevo_doc.png"))); // NOI18N
        btnregistrar.setText("INGRESAR");
        btnregistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnregistrar.setContentAreaFilled(false);
        btnregistrar.setEnabled(false);
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });

        btneliminar.setBackground(new java.awt.Color(255, 255, 255));
        btneliminar.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        btneliminar.setForeground(new java.awt.Color(111, 174, 2));
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eliminar_doc.png"))); // NOI18N
        btneliminar.setText("ELIMINAR");
        btneliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btneliminar.setContentAreaFilled(false);
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(111, 174, 2));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/guardar_doc.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(111, 174, 2));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Home_32px.png"))); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.setContentAreaFilled(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnconsultar1.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        btnconsultar1.setForeground(new java.awt.Color(111, 174, 2));
        btnconsultar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buscar_doc.png"))); // NOI18N
        btnconsultar1.setText("BUSCAR");
        btnconsultar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnconsultar1.setContentAreaFilled(false);
        btnconsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelbotonesLayout = new javax.swing.GroupLayout(panelbotones);
        panelbotones.setLayout(panelbotonesLayout);
        panelbotonesLayout.setHorizontalGroup(
            panelbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelbotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelbotonesLayout.createSequentialGroup()
                        .addComponent(btnregistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btneliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelbotonesLayout.createSequentialGroup()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(11, 11, 11)
                        .addComponent(btnconsultar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(11, 11, 11))))
            .addGroup(panelbotonesLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelbotonesLayout.setVerticalGroup(
            panelbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelbotonesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnregistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnconsultar1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jPanel1.add(panelbotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, 220));

        IngresoDatospanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INGRESO DATOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18), new java.awt.Color(111, 174, 2))); // NOI18N
        IngresoDatospanel.setOpaque(false);

        txtdoc.setBackground(new java.awt.Color(51, 51, 51));
        txtdoc.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtdoc.setForeground(new java.awt.Color(111, 174, 2));
        txtdoc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        txtdoc.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtdoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdocKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdocKeyTyped(evt);
            }
        });

        lblcodigo1.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblcodigo1.setForeground(new java.awt.Color(111, 174, 2));
        lblcodigo1.setText("DOCUMENTO");

        lblcodigo2.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblcodigo2.setForeground(new java.awt.Color(111, 174, 2));
        lblcodigo2.setText("NOMBRE");

        txtnombre.setEditable(false);
        txtnombre.setBackground(new java.awt.Color(51, 51, 51));
        txtnombre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(111, 174, 2));
        txtnombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        txtnombre.setEnabled(false);
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnombreKeyReleased(evt);
            }
        });

        lblcodigo3.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblcodigo3.setForeground(new java.awt.Color(111, 174, 2));
        lblcodigo3.setText("APELLIDO");

        txtapellido.setEditable(false);
        txtapellido.setBackground(new java.awt.Color(51, 51, 51));
        txtapellido.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtapellido.setForeground(new java.awt.Color(111, 174, 2));
        txtapellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        txtapellido.setEnabled(false);
        txtapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtapellidoKeyReleased(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(111, 174, 2));
        jLabel4.setText("*");

        jLabel5.setForeground(new java.awt.Color(111, 174, 2));
        jLabel5.setText("*");

        btnbuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnbuscar.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        btnbuscar.setForeground(new java.awt.Color(111, 174, 2));
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buscar_doc.png"))); // NOI18N
        btnbuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnbuscar.setContentAreaFilled(false);
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        btnlimpiar.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        btnlimpiar.setForeground(new java.awt.Color(111, 174, 2));
        btnlimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/borrar.png"))); // NOI18N
        btnlimpiar.setText("LIMPIAR");
        btnlimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnlimpiar.setContentAreaFilled(false);
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IngresoDatospanelLayout = new javax.swing.GroupLayout(IngresoDatospanel);
        IngresoDatospanel.setLayout(IngresoDatospanelLayout);
        IngresoDatospanelLayout.setHorizontalGroup(
            IngresoDatospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IngresoDatospanelLayout.createSequentialGroup()
                .addGroup(IngresoDatospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IngresoDatospanelLayout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addGroup(IngresoDatospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(IngresoDatospanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(IngresoDatospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtdoc, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(IngresoDatospanelLayout.createSequentialGroup()
                                .addComponent(lblcodigo1)
                                .addGap(112, 112, 112))
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IngresoDatospanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblcodigo2))
                    .addGroup(IngresoDatospanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblcodigo3))
                    .addGroup(IngresoDatospanelLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btnlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        IngresoDatospanelLayout.setVerticalGroup(
            IngresoDatospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IngresoDatospanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IngresoDatospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(IngresoDatospanelLayout.createSequentialGroup()
                        .addComponent(lblcodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(lblcodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(IngresoDatospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addComponent(lblcodigo3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(IngresoDatospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(103, 103, 103)
                .addComponent(btnlimpiar)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jPanel1.add(IngresoDatospanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 360, 510));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/registros.gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//METODO LISTAR
    metodosSQLEmpleado sql = new metodosSQLEmpleado();

    void listar() {
        String sql = "SELECT idempleado,empleados.documento,nombre,apellido,sueldo,trabajo FROM empleados,personas WHERE empleados.documento=personas.documento";
        try {
            cn = con.Conectarse();
            st = cn.createStatement();
            rs = st.executeQuery(sql);
            Object[] persona = new Object[6];
            modelo = (DefaultTableModel) jtRegistro1.getModel();
            while (rs.next()) {
                persona[0] = rs.getInt("idempleado");
                persona[1] = rs.getString("documento");
                persona[2] = rs.getString("nombre");
                persona[3] = rs.getString("apellido");
                persona[4] = rs.getDouble("sueldo");
                persona[5] = rs.getString("trabajo");

                modelo.addRow(persona);
            }
            jtRegistro1.setModel(modelo);
        } catch (Exception e) {
        }
    }

    void limpiartabla() {
        int filas = jtRegistro1.getRowCount();
        for (int i = 0; i < filas; i++) {
            modelo.removeRow(0);

        }
    }

    public void Clear() {

        txtnombre.setText("");
        txtapellido.setText("");
        txtid.setText("");
        txtSueldo.setText("");
        CBRol.setSelectedItem("Seleccione");
        CBRol.setEnabled(false);
        txtdoc.setEditable(true);
        txtdoc.setEnabled(true);
        txtSueldo.setEditable(false);
        txtSueldo.setEnabled(false);
        txtdoc.setText("");

    }
    private void lblminimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblminimizarMouseClicked
        this.setState(RegistroEmpleados.ICONIFIED);
    }//GEN-LAST:event_lblminimizarMouseClicked

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void txtidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidKeyReleased

    private void txtSueldoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSueldoKeyReleased

        Character validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "¡Ingrese solo números!", "MENSAJE DE ERROR", JOptionPane.ERROR_MESSAGE);
            txtSueldo.setText("");
        }
    }//GEN-LAST:event_txtSueldoKeyReleased

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
        int s = JOptionPane.showConfirmDialog(null, "Desea registrar este empleado", "Ingreso empleado confirmacion", 0);
        if (s == 0) {
            if (txtSueldo.getText().isEmpty()) {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "*CAMPOS OBLIGATORIOS", "INFORMATIVO", JOptionPane.INFORMATION_MESSAGE);
            } else {
                boolean estado = false;
                double sueldo = 0;
                try {
                    sueldo = Double.parseDouble(txtSueldo.getText());
                    estado = true;
                } catch (Exception e) {
                }
                //String buscar = metodosSQLEmpleados.BuscarNombre(txtdoc.getText());
                //String ver = metodosSQLEmpleados.BuscarApellido(txtdoc.getText());

                Empleados emp = new Empleados(txtdoc.getText(), sueldo, (String) CBRol.getSelectedItem(), estado);
                int i = sql.guardar(emp);
                if (i > 0) {
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(this, "EMPLEADO REGISTRADA CON EXITO", "INFORMATIVO", JOptionPane.INFORMATION_MESSAGE);
                    limpiartabla();
                    listar();
                    Clear();
                } else {
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(this, "NO REGISTRADO, YA EXISTE EL EMPLEADO", "ERROR", JOptionPane.ERROR_MESSAGE);

                }

                txtdoc.setEditable(true);
                txtdoc.setEnabled(true);
                txtdoc.setText("");
            }
        }
    }//GEN-LAST:event_btnregistrarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        int s = JOptionPane.showConfirmDialog(null, "Esta seguro de eliminar este empleado", "Aviso de Confirmacion", 0);
        if (s == 0) {
            int res = 0;
            int row = jtRegistro1.getSelectedRow();
            int fila = jtRegistro1.getSelectedColumnCount();
            if (fila < 1) {
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, "DEBE SELECCIONAR UN REGISTRO DE LA TABLA", "AVISO", JOptionPane.INFORMATION_MESSAGE);

            } else {
                res = sql.eliminarRegistro(jtRegistro1.getValueAt(row, 0).toString());
                if (res > 0) {
                    limpiartabla();
                    listar();
                    Clear();
                }
            }
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        int s = JOptionPane.showConfirmDialog(null, "Desea modificar al empleado", "Si/No", 0);
        if (s == 0) {
            if (txtSueldo.getText().isEmpty()) {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "*CAMPOS OBLIGATORIOS", "INFORMATIVO", JOptionPane.INFORMATION_MESSAGE);
            } else {

                double sueldo = 0;
                int id = 0;
                try {
                    sueldo = Double.parseDouble(txtSueldo.getText());
                    id = Integer.parseInt(txtid.getText());
                } catch (Exception e) {
                }

                Empleados emp = new Empleados(id, sueldo, (String) CBRol.getSelectedItem());
                int i = sql.actualizar(emp);

                if (i > 0) {
                    Toolkit.getDefaultToolkit().beep();

                    limpiartabla();
                    listar();
                    Clear();
                } else {
                    Toolkit.getDefaultToolkit().beep();

                }
                txtdoc.setEditable(true);
                txtdoc.setEnabled(true);
                txtdoc.setText("");
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnconsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultar1ActionPerformed

        BuscarEmpleados busca = new BuscarEmpleados(this, true);
        busca.setVisible(true);
        txtdoc.setEnabled(false);
        txtdoc.setEditable(false);
        txtSueldo.setEnabled(true);
        txtSueldo.setEditable(true);
        CBRol.setEnabled(true);
        //para los que no necesitan trasnformar
        txtdoc.setText(busca.getDocumentoper());
        txtnombre.setText(busca.getNombre());
        txtapellido.setText(busca.getApellido());
        try {
            String id = String.valueOf(busca.getId());
            txtid.setText(id);
            String sueldo = String.valueOf(busca.getSueldo());
            txtSueldo.setText(sueldo);
            CBRol.setSelectedItem(busca.getTrabajo());

        } catch (Exception e) {
            System.out.println(e);
        }


    }//GEN-LAST:event_btnconsultar1ActionPerformed

    private void txtnombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyReleased

    }//GEN-LAST:event_txtnombreKeyReleased

    private void txtapellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidoKeyReleased

    }//GEN-LAST:event_txtapellidoKeyReleased

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        Clear();
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed

        buscaDato(txtdoc.getText());

    }//GEN-LAST:event_btnbuscarActionPerformed

    private void jtRegistro1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtRegistro1MouseClicked
        // TODO add your handling code here:
        txtdoc.setEditable(false);
        txtdoc.setEnabled(false);
        int fila = jtRegistro1.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "EMPLEADO no seleccionada");
        } else {

            txtid.setText(jtRegistro1.getValueAt(fila, 0).toString());
            txtdoc.setText(jtRegistro1.getValueAt(fila, 1).toString());
            txtnombre.setText(jtRegistro1.getValueAt(fila, 2).toString());
            txtapellido.setText(jtRegistro1.getValueAt(fila, 3).toString());
            txtSueldo.setText(jtRegistro1.getValueAt(fila, 4).toString());
            CBRol.setSelectedItem(jtRegistro1.getValueAt(fila, 5).toString());
            txtSueldo.setEnabled(true);
            txtSueldo.setEditable(true);
            CBRol.setEnabled(true);

        }
    }//GEN-LAST:event_jtRegistro1MouseClicked

    private void txtdocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdocKeyTyped
        Character validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "¡Ingrese solo números!", "MENSAJE DE ERROR", JOptionPane.ERROR_MESSAGE);
            txtdoc.setText("");
        }

    }//GEN-LAST:event_txtdocKeyTyped

    private void txtSueldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSueldoKeyTyped
       
    }//GEN-LAST:event_txtSueldoKeyTyped

    private void CBRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBRolActionPerformed

    private void txtdocKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdocKeyReleased
        //MENOR A 10 CARACTERES
        if (txtdoc.getText().length() == 11) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(rootPane, "¡Debe tener 10 digitos!", "MENSAJE DE ERROR", JOptionPane.ERROR_MESSAGE);
            txtdoc.setText("");
        }

    }//GEN-LAST:event_txtdocKeyReleased

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBRol;
    private javax.swing.JPanel IngresoDatospanel;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btnconsultar1;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnregistrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtRegistro1;
    private javax.swing.JLabel lblcodigo1;
    private javax.swing.JLabel lblcodigo2;
    private javax.swing.JLabel lblcodigo3;
    private javax.swing.JLabel lblcodigo6;
    private javax.swing.JLabel lblcodigo7;
    private javax.swing.JLabel lblcodigo8;
    private javax.swing.JLabel lblminimizar;
    private javax.swing.JPanel panelbotones;
    private javax.swing.JPanel tablap;
    private javax.swing.JPanel tablap1;
    private javax.swing.JTextField txtSueldo;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtdoc;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
