/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.conexiones;
import Metodos.metodosSQLPersonas;
import Modelo.ImagenJChooser;
import Modelo.Persona;
import Modelo.Usuario;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class RegistroPersonas extends javax.swing.JFrame {

    /**
     * Creates new form RegistroPersonas
     */
    conexiones con = new conexiones();
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelo;
    int ng;
    String gener;

    public void setNg(int ng) {
        this.ng = ng;
    }

    public RegistroPersonas() {
        initComponents();

        btnmasculino.setSelected(true);
        this.setLocationRelativeTo(null);
        setIconImage(getIconImage());
        ImageIcon imagen = new ImageIcon("src/Images/usuariofoto.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(), Image.SCALE_DEFAULT));
        lblFoto.setIcon(icono);
        this.repaint();
        listar();
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Images/autoicon.jpg"));

        return retValue;
    }
    metodosSQLPersonas sql = new metodosSQLPersonas();

    //METODO LISTAR
    void listar() {
        String sql = "SELECT * FROM personas";
        try {
            cn = con.Conectarse();
            st = cn.createStatement();
            rs = st.executeQuery(sql);
            Object[] persona = new Object[6];
            modelo = (DefaultTableModel) jtRegistro.getModel();
            while (rs.next()) {
                persona[0] = rs.getString("tipo_documento");
                persona[1] = rs.getString("documento");
                persona[2] = rs.getString("nombre");
                persona[3] = rs.getString("apellido");
                persona[4] = rs.getString("genero");
                persona[5] = rs.getDate("fecha_nacimiento");

                modelo.addRow(persona);

            }
            jtRegistro.setModel(modelo);
        } catch (Exception e) {
        }
    }

    void limpiartabla() {
        int filas = jtRegistro.getRowCount();
        for (int i = 0; i < filas; i++) {
            modelo.removeRow(0);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelbotones = new javax.swing.JPanel();
        btnregistrar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnconsultar1 = new javax.swing.JButton();
        IngresoDatospanel = new javax.swing.JPanel();
        lblcodigo = new javax.swing.JLabel();
        txtdoc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CBDocumento = new javax.swing.JComboBox<>();
        lblcodigo1 = new javax.swing.JLabel();
        lblcodigo2 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        lblcodigo3 = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        lblcodigo4 = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        lblcodigo5 = new javax.swing.JLabel();
        btnfemenino = new javax.swing.JRadioButton();
        btnmasculino = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnborrar = new javax.swing.JButton();
        lblminimizar = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        tablap = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtRegistro = new javax.swing.JTable();
        tablap1 = new javax.swing.JPanel();
        lblFoto = new javax.swing.JLabel();
        btncargar = new javax.swing.JButton();
        tablap2 = new javax.swing.JPanel();
        txtruta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(111, 174, 2), 5, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/registros.gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 240, 280));

        panelbotones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bradley Hand ITC", 1, 14), new java.awt.Color(111, 174, 2))); // NOI18N
        panelbotones.setOpaque(false);

        btnregistrar.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        btnregistrar.setForeground(new java.awt.Color(111, 174, 2));
        btnregistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nuevo_doc.png"))); // NOI18N
        btnregistrar.setText("INGRESAR");
        btnregistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnregistrar.setContentAreaFilled(false);
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });

        btneliminar.setBackground(new java.awt.Color(255, 255, 255));
        btneliminar.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        btneliminar.setForeground(new java.awt.Color(111, 174, 2));
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eliminar_doc.png"))); // NOI18N
        btneliminar.setText("ELIMINAR");
        btneliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btneliminar.setContentAreaFilled(false);
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(111, 174, 2));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/guardar_doc.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(111, 174, 2));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Home_32px.png"))); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.setContentAreaFilled(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnconsultar1.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        btnconsultar1.setForeground(new java.awt.Color(111, 174, 2));
        btnconsultar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buscar_doc.png"))); // NOI18N
        btnconsultar1.setText("BUSCAR");
        btnconsultar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnconsultar1.setContentAreaFilled(false);
        btnconsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelbotonesLayout = new javax.swing.GroupLayout(panelbotones);
        panelbotones.setLayout(panelbotonesLayout);
        panelbotonesLayout.setHorizontalGroup(
            panelbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelbotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelbotonesLayout.createSequentialGroup()
                        .addComponent(btnregistrar)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(panelbotonesLayout.createSequentialGroup()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnconsultar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(11, 11, 11))))
            .addGroup(panelbotonesLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelbotonesLayout.setVerticalGroup(
            panelbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelbotonesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnregistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnconsultar1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel1.add(panelbotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 280, 220));

        IngresoDatospanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INGRESO DATOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18), new java.awt.Color(111, 174, 2))); // NOI18N
        IngresoDatospanel.setOpaque(false);

        lblcodigo.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblcodigo.setForeground(new java.awt.Color(111, 174, 2));
        lblcodigo.setText("TIPO DOCUMENTO");

        txtdoc.setBackground(new java.awt.Color(51, 51, 51));
        txtdoc.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtdoc.setForeground(new java.awt.Color(111, 174, 2));
        txtdoc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        txtdoc.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtdoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdocKeyReleased(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(111, 174, 2));
        jLabel2.setText("*");

        CBDocumento.setBackground(new java.awt.Color(51, 51, 51));
        CBDocumento.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CBDocumento.setForeground(new java.awt.Color(111, 174, 2));
        CBDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "CC", "CE", "Pasaporte", "TI", "RC" }));
        CBDocumento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CBDocumento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CBDocumento.setOpaque(false);

        lblcodigo1.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblcodigo1.setForeground(new java.awt.Color(111, 174, 2));
        lblcodigo1.setText("DOCUMENTO");

        lblcodigo2.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblcodigo2.setForeground(new java.awt.Color(111, 174, 2));
        lblcodigo2.setText("NOMBRE");

        txtnombre.setBackground(new java.awt.Color(51, 51, 51));
        txtnombre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(111, 174, 2));
        txtnombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnombreKeyReleased(evt);
            }
        });

        lblcodigo3.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblcodigo3.setForeground(new java.awt.Color(111, 174, 2));
        lblcodigo3.setText("APELLIDO");

        txtapellido.setBackground(new java.awt.Color(51, 51, 51));
        txtapellido.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtapellido.setForeground(new java.awt.Color(111, 174, 2));
        txtapellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        txtapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtapellidoKeyReleased(evt);
            }
        });

        lblcodigo4.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblcodigo4.setForeground(new java.awt.Color(111, 174, 2));
        lblcodigo4.setText("fecha nacimiento");

        date.setBackground(new java.awt.Color(0, 0, 0));
        date.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(111, 174, 2), 2, true));
        date.setForeground(new java.awt.Color(111, 174, 2));
        date.setDateFormatString("yyyy-MM-dd");
        date.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        lblcodigo5.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblcodigo5.setForeground(new java.awt.Color(111, 174, 2));
        lblcodigo5.setText("GENERO:");

        btnfemenino.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(btnfemenino);
        btnfemenino.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        btnfemenino.setForeground(new java.awt.Color(111, 174, 2));
        btnfemenino.setText("FEMENINO");
        btnfemenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfemeninoActionPerformed(evt);
            }
        });

        btnmasculino.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(btnmasculino);
        btnmasculino.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        btnmasculino.setForeground(new java.awt.Color(111, 174, 2));
        btnmasculino.setText("Masculino");
        btnmasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmasculinoActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(111, 174, 2));
        jLabel4.setText("*");

        jLabel5.setForeground(new java.awt.Color(111, 174, 2));
        jLabel5.setText("*");

        btnborrar.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        btnborrar.setForeground(new java.awt.Color(111, 174, 2));
        btnborrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/borrar.png"))); // NOI18N
        btnborrar.setText("LIMPIAR");
        btnborrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnborrar.setContentAreaFilled(false);
        btnborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IngresoDatospanelLayout = new javax.swing.GroupLayout(IngresoDatospanel);
        IngresoDatospanel.setLayout(IngresoDatospanelLayout);
        IngresoDatospanelLayout.setHorizontalGroup(
            IngresoDatospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IngresoDatospanelLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(btnmasculino)
                .addGap(18, 18, 18)
                .addComponent(btnfemenino)
                .addGap(67, 67, 67))
            .addGroup(IngresoDatospanelLayout.createSequentialGroup()
                .addGroup(IngresoDatospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IngresoDatospanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(IngresoDatospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblcodigo)
                            .addComponent(lblcodigo1)
                            .addGroup(IngresoDatospanelLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(IngresoDatospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CBDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtdoc, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(IngresoDatospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblcodigo2)
                            .addComponent(lblcodigo3)
                            .addComponent(lblcodigo4)
                            .addComponent(lblcodigo5)))
                    .addGroup(IngresoDatospanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(IngresoDatospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(IngresoDatospanelLayout.createSequentialGroup()
                    .addGap(110, 110, 110)
                    .addComponent(btnborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(116, Short.MAX_VALUE)))
        );
        IngresoDatospanelLayout.setVerticalGroup(
            IngresoDatospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IngresoDatospanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(CBDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblcodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IngresoDatospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblcodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IngresoDatospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblcodigo3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IngresoDatospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(lblcodigo5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(IngresoDatospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnfemenino)
                    .addComponent(btnmasculino))
                .addGap(18, 18, 18)
                .addComponent(lblcodigo4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(IngresoDatospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IngresoDatospanelLayout.createSequentialGroup()
                    .addContainerGap(430, Short.MAX_VALUE)
                    .addComponent(btnborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(28, 28, 28)))
        );

        jPanel1.add(IngresoDatospanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 360, 530));

        lblminimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Expand_Arrow_32px.png"))); // NOI18N
        lblminimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblminimizarMouseClicked(evt);
            }
        });
        jPanel1.add(lblminimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 10, 40, 30));

        btnCerrar.setBackground(new java.awt.Color(0, 0, 0));
        btnCerrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Delete_32px.png"))); // NOI18N
        btnCerrar.setAutoscrolls(true);
        btnCerrar.setBorder(null);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCerrar.setOpaque(true);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, -1, -1));

        tablap.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTROS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18), new java.awt.Color(111, 174, 2))); // NOI18N
        tablap.setOpaque(false);

        jtRegistro.setBackground(new java.awt.Color(111, 174, 2));
        jtRegistro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(111, 174, 2), 3, true));
        jtRegistro.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jtRegistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TIPO DOC", "DOCUMENTO", "NOMBRE", "APELLIDO", "GENERO", "FECHA NACIMIENTO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtRegistro.setSelectionBackground(new java.awt.Color(102, 204, 0));
        jtRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtRegistroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtRegistro);

        javax.swing.GroupLayout tablapLayout = new javax.swing.GroupLayout(tablap);
        tablap.setLayout(tablapLayout);
        tablapLayout.setHorizontalGroup(
            tablapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
        );
        tablapLayout.setVerticalGroup(
            tablapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablapLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(tablap, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 560, 200));

        tablap1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FOTO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18), new java.awt.Color(111, 174, 2))); // NOI18N
        tablap1.setOpaque(false);

        lblFoto.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblFoto.setForeground(new java.awt.Color(111, 174, 2));
        lblFoto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(111, 174, 2), 4, true));

        btncargar.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        btncargar.setForeground(new java.awt.Color(111, 174, 2));
        btncargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/camara.png"))); // NOI18N
        btncargar.setText("CARGAR");
        btncargar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncargar.setContentAreaFilled(false);
        btncargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tablap1Layout = new javax.swing.GroupLayout(tablap1);
        tablap1.setLayout(tablap1Layout);
        tablap1Layout.setHorizontalGroup(
            tablap1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablap1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(tablap1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tablap1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btncargar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        tablap1Layout.setVerticalGroup(
            tablap1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablap1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncargar, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(tablap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 230, 290));

        tablap2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RUTA/FOTO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18), new java.awt.Color(111, 174, 2))); // NOI18N
        tablap2.setOpaque(false);

        txtruta.setEditable(false);
        txtruta.setBackground(new java.awt.Color(51, 51, 51));
        txtruta.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtruta.setForeground(new java.awt.Color(111, 174, 2));
        txtruta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        txtruta.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtruta.setEnabled(false);

        javax.swing.GroupLayout tablap2Layout = new javax.swing.GroupLayout(tablap2);
        tablap2.setLayout(tablap2Layout);
        tablap2Layout.setHorizontalGroup(
            tablap2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtruta, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
        );
        tablap2Layout.setVerticalGroup(
            tablap2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablap2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(tablap2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 90, 270, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1241, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btncargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncargarActionPerformed
        JFileChooser j = new JFileChooser();
        //j.setCurrentDirectory(new File("ruta de archivo a recordar"));
        FileNameExtensionFilter fil = new FileNameExtensionFilter("JPG, PNG & GIF", "jpg", "png", "gif");
        j.setFileFilter(fil);
        j.setCurrentDirectory(new File("Fotos"));
        ImagenJChooser preview = new ImagenJChooser();
        j.setAccessory(preview);
        j.addPropertyChangeListener(preview);

        int el = j.showOpenDialog(this);
        if (el == JFileChooser.APPROVE_OPTION) {
            txtruta.setText(j.getSelectedFile().getAbsolutePath());
            Image img = new ImageIcon(txtruta.getText()).getImage();
            ImageIcon img2 = new ImageIcon(img.getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(), Image.SCALE_DEFAULT));
            lblFoto.setIcon(img2);
        }

    }//GEN-LAST:event_btncargarActionPerformed

    public void Clear() {
        ImageIcon imagen = new ImageIcon("src/Images/usuariofoto.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(), Image.SCALE_DEFAULT));
        lblFoto.setIcon(icono);
        this.repaint();
        CBDocumento.setSelectedItem("Seleccione");
        txtdoc.setText("");
        txtnombre.setText("");
        txtruta.setText("");
        txtapellido.setText("");
        date.setDate(null);

    }
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        int s = JOptionPane.showConfirmDialog(null, "Esta seguro de modificar este registro", "Si/No", 0);
        if (s == 0) {
            if (txtnombre.getText().isEmpty() || txtapellido.getText().isEmpty() || txtdoc.getText().isEmpty()) {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "*CAMPOS OBLIGATORIOS");
            } else {
                boolean estado = false;
                if (ng == 0) {
                    gener = "Masculino";
                    estado = true;
                } else {
                    if (ng == 1) {
                        gener = "Femenino";
                        estado = true;
                    }
                }
                java.sql.Date fecha = null;
                Date dia = date.getDate();
                if (dia != null) {
                    long d = dia.getTime();
                    fecha = new java.sql.Date(d);

                } else {
                    Date dates = new Date();
                    DateFormat formato = new SimpleDateFormat("dd-MM-yyyy");
                    formato.format(dates);
                    date.setDate(dates);
                    long d = dia.getTime();
                    fecha = new java.sql.Date(d);
                }
                Persona people = new Persona((String) CBDocumento.getSelectedItem(), txtdoc.getText(), txtnombre.getText(), txtapellido.getText(), fecha, gener, estado);
                File ruta = new File(txtruta.getText());
                try {
                    byte[] icono = new byte[(int) ruta.length()];
                    InputStream input = new FileInputStream(ruta);
                    input.read(icono);
                    people.setFoto(icono);
                } catch (Exception ex) {
                    people.setFoto(null);
                }
                int res = sql.actualizar(people);
                if (res > 0) {
                    Toolkit.getDefaultToolkit().beep();
                    limpiartabla();
                    listar();
                    Clear();
                } else {
                    Toolkit.getDefaultToolkit().beep();
                    txtdoc.setEditable(true);
                    txtdoc.setEnabled(true);
                    txtdoc.setText("");

                }
            }
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        int s = JOptionPane.showConfirmDialog(null, "Esta seguro de eliminar este registro", "Si/No", 0);
        if (s == 0) {
            int res = 0;
            int row = jtRegistro.getSelectedRow();
            int fila = jtRegistro.getSelectedColumnCount();
            if (fila < 1) {
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, "DEBE SELECCIONAR UN REGISTRO DE LA TABLA", "AVISO", JOptionPane.INFORMATION_MESSAGE);

            } else {
                res = sql.eliminarRegistro(jtRegistro.getValueAt(row, 1).toString());
                if (res > 0) {
                    limpiartabla();
                    listar();
                    Clear();
                }
            }
        }

    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
        int s = JOptionPane.showConfirmDialog(null, "Desea registrar esta persona", "Si/No", 0);
        if (s == 0) {
            if (txtnombre.getText().isEmpty() || txtapellido.getText().isEmpty() || txtdoc.getText().isEmpty()) {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "*CAMPOS OBLIGATORIOS", "INFORMATIVO", JOptionPane.INFORMATION_MESSAGE);
            } else {
                boolean estado = false;
                if (ng == 0) {
                    gener = "Masculino";
                    estado = true;
                } else {
                    if (ng == 1) {
                        gener = "Femenino";
                        estado = true;
                    }
                }
                java.sql.Date fecha = null;
                Date dia = date.getDate();
                if (dia != null) {
                    long d = dia.getTime();
                    fecha = new java.sql.Date(d);

                } else {
                    Date dates = new Date();
                    DateFormat formato = new SimpleDateFormat("dd-MM-yyyy");
                    formato.format(dates);
                    date.setDate(dates);
                    long d = dia.getTime();
                    fecha = new java.sql.Date(d);
                }

                Persona people = new Persona((String) CBDocumento.getSelectedItem(), txtdoc.getText(), txtnombre.getText(), txtapellido.getText(), fecha, gener, estado);
                File ruta = new File(txtruta.getText());
                try {
                    byte[] icono = new byte[(int) ruta.length()];
                    InputStream input = new FileInputStream(ruta);
                    input.read(icono);
                    people.setFoto(icono);
                } catch (Exception ex) {
                    people.setFoto(null);
                }
                int i = sql.guardar(people);

                if (i > 0) {
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(this, "PERSONA REGISTRADA CON EXITO", "INFORMATIVO", JOptionPane.INFORMATION_MESSAGE);
                    limpiartabla();
                    listar();
                    Clear();
                } else {
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(this, "NO REGISTRADO, YA EXISTE EL DOCUMENTO DE IDENTIFICACION", "ERROR", JOptionPane.ERROR_MESSAGE);
                    txtdoc.setEditable(true);
                    txtdoc.setEnabled(true);
                    txtdoc.setText("");

                }
            }
        }
    }//GEN-LAST:event_btnregistrarActionPerformed

    private void btnconsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultar1ActionPerformed
        BuscarPersonas busca = new BuscarPersonas(this, true);
        busca.setVisible(true);
        txtdoc.setEditable(false);
        txtdoc.setEnabled(false);
        CBDocumento.setSelectedItem(busca.getTipo_documento());
        txtdoc.setText(busca.getDocumento());
        txtnombre.setText(busca.getNombre());
        txtapellido.setText(busca.getApellido());
        String genero=busca.getGenero();
        try{
        if (genero.compareTo("Masculino") == 0) {
            this.btnmasculino.setSelected(true);
            this.btnfemenino.setSelected(false);
        } else if (genero.compareToIgnoreCase("Femenino") == 0) {
            this.btnmasculino.setSelected(false);
            this.btnfemenino.setSelected(true);

        }
        }catch(Exception ex){
        }
        date.setDate(busca.getDat());
         try {
                lblFoto.setIcon(sql.Icon(busca.getDocumento()));
            } catch (Exception e) {

            }

    }//GEN-LAST:event_btnconsultar1ActionPerformed

    private void lblminimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblminimizarMouseClicked
        this.setState(RegistroPersonas.ICONIFIED);
    }//GEN-LAST:event_lblminimizarMouseClicked

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void jtRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtRegistroMouseClicked
        txtdoc.setEditable(false);
        txtdoc.setEnabled(false);
        int fila = jtRegistro.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Persona no seleccionada");
        } else {

            CBDocumento.setSelectedItem(jtRegistro.getValueAt(fila, 0).toString());
            txtdoc.setText(jtRegistro.getValueAt(fila, 1).toString());
            txtnombre.setText(jtRegistro.getValueAt(fila, 2).toString());
            txtapellido.setText(jtRegistro.getValueAt(fila, 3).toString());
            String genero = jtRegistro.getValueAt(fila, 4).toString();
            //java.sql.Date fecha = (java.sql.Date) jtRegistro.getValueAt(fila, 5);
            String fecha = jtRegistro.getValueAt(fila, 5).toString();
            Date dat;
            try {
                lblFoto.setIcon(sql.Icon(txtdoc.getText()));
            } catch (Exception e) {

            }
            try {
                dat = new SimpleDateFormat("yyyy-MM-dd").parse(fecha);
                date.setDate(dat);
            } catch (ParseException e) {
                getToolkit().beep();
                System.out.println("Eror en fecha de ingreso");
            }
            if (genero.compareTo("Masculino") == 0) {
                this.btnmasculino.setSelected(true);
                this.btnfemenino.setSelected(false);
            } else if (genero.compareToIgnoreCase("Femenino") == 0) {
                this.btnmasculino.setSelected(false);
                this.btnfemenino.setSelected(true);

            }

        }
    }//GEN-LAST:event_jtRegistroMouseClicked

    private void btnborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarActionPerformed
        Clear();
        txtdoc.setEditable(true);
        txtdoc.setEnabled(true);
    }//GEN-LAST:event_btnborrarActionPerformed

    private void btnfemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfemeninoActionPerformed
        ng = 1;
        this.setNg(ng);
    }//GEN-LAST:event_btnfemeninoActionPerformed

    private void txtnombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyReleased
        //VALIDACIONES
        Character validar = evt.getKeyChar();
        //NO TENGAN LETRAS
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "¡Ingrese solo letras!", "MENSAJE DE ERROR", JOptionPane.ERROR_MESSAGE);
            txtnombre.setText("");
        }
    }//GEN-LAST:event_txtnombreKeyReleased

    private void txtapellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidoKeyReleased
        //VALIDACIONES
        Character validar = evt.getKeyChar();
        //NO TENGAN LETRAS
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "¡Ingrese solo letras!", "MENSAJE DE ERROR", JOptionPane.ERROR_MESSAGE);
            txtapellido.setText("");
        }
    }//GEN-LAST:event_txtapellidoKeyReleased

    private void btnmasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmasculinoActionPerformed
        ng = 0;
        this.setNg(ng);
    }//GEN-LAST:event_btnmasculinoActionPerformed

    private void txtdocKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdocKeyReleased
        //MENOR A 10 CARACTERES
        if (txtdoc.getText().length() == 11) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(rootPane, "¡Debe tener 10 digitos!", "MENSAJE DE ERROR", JOptionPane.ERROR_MESSAGE);
            txtdoc.setText("");
        }
    }//GEN-LAST:event_txtdocKeyReleased

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBDocumento;
    private javax.swing.JPanel IngresoDatospanel;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnborrar;
    private javax.swing.JButton btncargar;
    private javax.swing.JButton btnconsultar1;
    private javax.swing.JButton btneliminar;
    private javax.swing.JRadioButton btnfemenino;
    private javax.swing.JRadioButton btnmasculino;
    private javax.swing.JButton btnregistrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtRegistro;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JLabel lblcodigo1;
    private javax.swing.JLabel lblcodigo2;
    private javax.swing.JLabel lblcodigo3;
    private javax.swing.JLabel lblcodigo4;
    private javax.swing.JLabel lblcodigo5;
    private javax.swing.JLabel lblminimizar;
    private javax.swing.JPanel panelbotones;
    private javax.swing.JPanel tablap;
    private javax.swing.JPanel tablap1;
    private javax.swing.JPanel tablap2;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtdoc;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtruta;
    // End of variables declaration//GEN-END:variables
}
