/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Metodos.metodosSQLUsuario;
import Modelo.Usuario;
import java.awt.Color;
import java.awt.Image;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author RojeruSan
 */
public class RegistroUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public RegistroUsuarios() {
        initComponents();
        this.setLocationRelativeTo(this);
        setIconImage(getIconImage());
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Images/autoicon.jpg"));

        return retValue;
    }
    metodosSQLUsuario sql = new metodosSQLUsuario();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        lblapellido = new javax.swing.JLabel();
        lblpass = new javax.swing.JLabel();
        lblrango = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        jtxtpcont = new javax.swing.JPasswordField();
        cboxrango = new javax.swing.JComboBox<>();
        lblnombre1 = new javax.swing.JLabel();
        lblnombre2 = new javax.swing.JLabel();
        lblnombre3 = new javax.swing.JLabel();
        lblnombre4 = new javax.swing.JLabel();
        lblpass1 = new javax.swing.JLabel();
        lblnombre7 = new javax.swing.JLabel();
        txtrecuperar = new javax.swing.JTextField();
        lblminimizar = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnregistro = new javax.swing.JButton();
        lblnombre5 = new javax.swing.JLabel();
        lblnombre6 = new javax.swing.JLabel();
        aqui = new javax.swing.JLabel();
        jcboxMostarPass = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(111, 174, 2), 5, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(656, 443));

        pnlMenu.setBackground(new java.awt.Color(0, 0, 0));
        pnlMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(111, 174, 2), 3, true));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/usuario.png"))); // NOI18N

        lblnombre.setFont(new java.awt.Font("Engravers MT", 1, 15)); // NOI18N
        lblnombre.setForeground(new java.awt.Color(111, 174, 2));
        lblnombre.setText("NOMBRE:");

        lblusuario.setFont(new java.awt.Font("Engravers MT", 1, 15)); // NOI18N
        lblusuario.setForeground(new java.awt.Color(111, 174, 2));
        lblusuario.setText("USUARIo:");

        lblapellido.setFont(new java.awt.Font("Engravers MT", 1, 15)); // NOI18N
        lblapellido.setForeground(new java.awt.Color(111, 174, 2));
        lblapellido.setText("APELLIDO:");

        lblpass.setFont(new java.awt.Font("Engravers MT", 1, 15)); // NOI18N
        lblpass.setForeground(new java.awt.Color(111, 174, 2));
        lblpass.setText("PASSWORD:");

        lblrango.setFont(new java.awt.Font("Engravers MT", 1, 15)); // NOI18N
        lblrango.setForeground(new java.awt.Color(111, 174, 2));
        lblrango.setText("RANGO:");

        txtusuario.setBackground(new java.awt.Color(33, 33, 33));
        txtusuario.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtusuario.setForeground(new java.awt.Color(111, 174, 2));
        txtusuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });

        txtnombre.setBackground(new java.awt.Color(33, 33, 33));
        txtnombre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtnombre.setForeground(new java.awt.Color(111, 174, 2));
        txtnombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        txtnombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnombreKeyReleased(evt);
            }
        });

        txtapellido.setBackground(new java.awt.Color(33, 33, 33));
        txtapellido.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtapellido.setForeground(new java.awt.Color(111, 174, 2));
        txtapellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        txtapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellidoActionPerformed(evt);
            }
        });
        txtapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtapellidoKeyReleased(evt);
            }
        });

        jtxtpcont.setBackground(new java.awt.Color(51, 51, 51));
        jtxtpcont.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtpcont.setForeground(new java.awt.Color(111, 174, 2));
        jtxtpcont.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));

        cboxrango.setBackground(new java.awt.Color(0, 0, 0));
        cboxrango.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cboxrango.setForeground(new java.awt.Color(111, 174, 2));
        cboxrango.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OPCIONES", "ADMINISTRADOR", "USUARIO" }));
        cboxrango.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(111, 174, 2), 1, true));
        cboxrango.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblnombre1.setFont(new java.awt.Font("Engravers MT", 1, 15)); // NOI18N
        lblnombre1.setForeground(new java.awt.Color(111, 174, 2));
        lblnombre1.setText("*");

        lblnombre2.setFont(new java.awt.Font("Engravers MT", 1, 15)); // NOI18N
        lblnombre2.setForeground(new java.awt.Color(111, 174, 2));
        lblnombre2.setText("*");

        lblnombre3.setFont(new java.awt.Font("Engravers MT", 1, 15)); // NOI18N
        lblnombre3.setForeground(new java.awt.Color(111, 174, 2));
        lblnombre3.setText("*");

        lblnombre4.setFont(new java.awt.Font("Engravers MT", 1, 15)); // NOI18N
        lblnombre4.setForeground(new java.awt.Color(111, 174, 2));
        lblnombre4.setText("*");

        lblpass1.setFont(new java.awt.Font("Engravers MT", 1, 15)); // NOI18N
        lblpass1.setForeground(new java.awt.Color(111, 174, 2));
        lblpass1.setText("COD/RECUPERAR");

        lblnombre7.setFont(new java.awt.Font("Engravers MT", 1, 15)); // NOI18N
        lblnombre7.setForeground(new java.awt.Color(111, 174, 2));
        lblnombre7.setText("*");

        txtrecuperar.setBackground(new java.awt.Color(33, 33, 33));
        txtrecuperar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtrecuperar.setForeground(new java.awt.Color(111, 174, 2));
        txtrecuperar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        txtrecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrecuperarActionPerformed(evt);
            }
        });
        txtrecuperar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtrecuperarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblnombre)
                    .addComponent(lblapellido)
                    .addComponent(lblusuario)
                    .addComponent(lblpass)
                    .addComponent(lblrango)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cboxrango, javax.swing.GroupLayout.Alignment.LEADING, 0, 159, Short.MAX_VALUE)
                            .addComponent(txtnombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtusuario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtapellido, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtpcont, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblnombre1)
                            .addComponent(lblnombre2)
                            .addComponent(lblnombre3)
                            .addComponent(lblnombre4)))
                    .addComponent(lblpass1)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addComponent(txtrecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblnombre7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblnombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnombre1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblapellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnombre2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblusuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnombre3))
                .addGap(18, 18, 18)
                .addComponent(lblpass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtpcont, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnombre4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblrango)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboxrango, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblpass1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombre7)
                    .addComponent(txtrecuperar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        lblminimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Expand_Arrow_32px.png"))); // NOI18N
        lblminimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblminimizarMouseClicked(evt);
            }
        });

        btnCerrar.setBackground(new java.awt.Color(0, 0, 0));
        btnCerrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Delete_32px.png"))); // NOI18N
        btnCerrar.setAutoscrolls(true);
        btnCerrar.setBorder(null);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCerrar.setOpaque(true);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Menu_32px.png"))); // NOI18N
        btnMenu.setBorder(null);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMenu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Expand_Arrow_32px.png"))); // NOI18N
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/carro.gif"))); // NOI18N
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(111, 174, 2), 3, true));

        btnregistro.setBackground(new java.awt.Color(0, 0, 0));
        btnregistro.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        btnregistro.setForeground(new java.awt.Color(111, 174, 2));
        btnregistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Mouse_32px.png"))); // NOI18N
        btnregistro.setText("REGISTRARSE");
        btnregistro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(111, 174, 2), 3, true));
        btnregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistroActionPerformed(evt);
            }
        });

        lblnombre5.setFont(new java.awt.Font("Engravers MT", 1, 15)); // NOI18N
        lblnombre5.setForeground(new java.awt.Color(111, 174, 2));
        lblnombre5.setText("¿OLVIDASTE TU USUARIO O CONTRASEÑA?");

        lblnombre6.setFont(new java.awt.Font("Engravers MT", 1, 15)); // NOI18N
        lblnombre6.setForeground(new java.awt.Color(111, 174, 2));
        lblnombre6.setText("CLIC ");

        aqui.setFont(new java.awt.Font("Engravers MT", 1, 15)); // NOI18N
        aqui.setForeground(new java.awt.Color(111, 174, 2));
        aqui.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aqui.setText("aquí");
        aqui.setToolTipText("<html>\n<head>\n<style>\n#contenedor{background:#00688B;color:white;\npadding-left:10px;padding-right:10px;margin:0;\npadding-top:5px;padding-bottom:5px;}\n</style>\n</head>\n<body>\n<h4 id=\"contenedor\">Recuperar</h4>\n</body>\n</html>");
        aqui.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aqui.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                aquiMouseMoved(evt);
            }
        });
        aqui.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aquiMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aquiMouseExited(evt);
            }
        });

        jcboxMostarPass.setBackground(new java.awt.Color(0, 0, 0));
        jcboxMostarPass.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jcboxMostarPass.setForeground(new java.awt.Color(111, 174, 2));
        jcboxMostarPass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(111, 174, 2), 2, true));
        jcboxMostarPass.setLabel("Show Password");
        jcboxMostarPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboxMostarPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblnombre5)
                                .addGap(0, 16, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblminimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(100, 100, 100)
                                    .addComponent(jLabel2))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(37, 37, 37)
                                    .addComponent(btnregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(152, 152, 152)
                                    .addComponent(lblnombre6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(aqui)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jcboxMostarPass, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(313, 313, 313))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblminimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(btnregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblnombre5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombre6)
                    .addComponent(aqui, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jcboxMostarPass)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed

        Login log = new Login();
        log.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        int posicion = btnMenu.getX();
        if (posicion > 5) {
            Animacion.Animacion.mover_izquierda(211, 5, 2, 2, btnMenu);
            Animacion.Animacion.mover_izquierda(5, -200, 2, 2, pnlMenu);
        } else {
            Animacion.Animacion.mover_derecha(5, 210, 2, 2, btnMenu);
            Animacion.Animacion.mover_derecha(-200, 5, 2, 2, pnlMenu);
        }
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistroActionPerformed
        int s = JOptionPane.showConfirmDialog(null, "Esta seguro de registrar este usuario", "Si/No", 0);
        if (s == 0) {
            if (txtnombre.getText().isEmpty() || txtapellido.getText().isEmpty() || txtusuario.getText().isEmpty() || jtxtpcont.getText().isEmpty() || txtrecuperar.getText().isEmpty()) {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "*CAMPOS OBLIGATORIOS");
            } else {
                boolean estado;
                int rol;
                if (cboxrango.getSelectedItem().equals("ADMINISTRADOR")) {
                    rol = 1;
                    estado = true;
                } else {
                    rol = 2;
                    estado = true;
                }
                Usuario u = new Usuario(txtnombre.getText(), txtapellido.getText(), txtusuario.getText(), jtxtpcont.getText(), (String) cboxrango.getSelectedItem(), estado, rol, txtrecuperar.getText());
                int i = sql.guardar(u);

                if (i > 0) {
                    JOptionPane.showMessageDialog(this, "USUARIO REGISTRADO");
                    txtnombre.setText("");
                    txtapellido.setText("");
                    txtusuario.setText("");
                    jtxtpcont.setText("");
                    cboxrango.setSelectedItem("OPCIONES");
                    txtrecuperar.setText("");
                } else {
                    Toolkit.getDefaultToolkit().beep();
                    JOptionPane.showMessageDialog(this, "NO REGISTRADO, YA EXISTE EL USUARIO");
                    txtusuario.setText("");

                }
            }
        }

    }//GEN-LAST:event_btnregistroActionPerformed

    private void lblminimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblminimizarMouseClicked
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_lblminimizarMouseClicked

    private void aquiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aquiMouseClicked
        Recuperar rec = new Recuperar(this, true);
        rec.setVisible(true);
    }//GEN-LAST:event_aquiMouseClicked

    private void aquiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aquiMouseExited
        this.aqui.setForeground(new Color(111, 174, 2));
    }//GEN-LAST:event_aquiMouseExited

    private void aquiMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aquiMouseMoved
        this.aqui.setForeground(new Color(51, 153, 255));
    }//GEN-LAST:event_aquiMouseMoved

    private void txtapellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidoKeyReleased
        //VALIDACIONES
        Character validar = evt.getKeyChar();
        //NO TENGAN LETRAS
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "¡Ingrese solo letras!", "MENSAJE DE ERROR", JOptionPane.ERROR_MESSAGE);
            txtapellido.setText("");
        }
    }//GEN-LAST:event_txtapellidoKeyReleased

    private void txtapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidoActionPerformed

    private void txtnombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyReleased
        //VALIDACIONES
        Character validar = evt.getKeyChar();
        //NO TENGAN NUMEROS
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "¡Ingrese solo letras!", "MENSAJE DE ERROR", JOptionPane.ERROR_MESSAGE);
            txtnombre.setText("");
        }
    }//GEN-LAST:event_txtnombreKeyReleased

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioActionPerformed

    private void txtrecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrecuperarActionPerformed

    }//GEN-LAST:event_txtrecuperarActionPerformed

    private void txtrecuperarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrecuperarKeyReleased
        //MENOR A 10 CARACTERES
        if (txtrecuperar.getText().length() == 11) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(rootPane, "¡Debe tener 10 letras!", "MENSAJE DE ERROR", JOptionPane.ERROR_MESSAGE);
            txtrecuperar.setText("");
        }
        //VALIDACIONES
        Character validar = evt.getKeyChar();
        //NO TENGAN NUMEROS
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "¡Ingrese solo letras!", "MENSAJE DE ERROR", JOptionPane.ERROR_MESSAGE);
            txtrecuperar.setText("");
        }

    }//GEN-LAST:event_txtrecuperarKeyReleased

    private void jcboxMostarPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboxMostarPassActionPerformed
        if(jcboxMostarPass.isSelected()){
            jtxtpcont.setEchoChar((char)0);
        }else{
            jtxtpcont.setEchoChar('*');
        }
    }//GEN-LAST:event_jcboxMostarPassActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aqui;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnregistro;
    private javax.swing.JComboBox<String> cboxrango;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox jcboxMostarPass;
    private javax.swing.JPasswordField jtxtpcont;
    private javax.swing.JLabel lblapellido;
    private javax.swing.JLabel lblminimizar;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblnombre1;
    private javax.swing.JLabel lblnombre2;
    private javax.swing.JLabel lblnombre3;
    private javax.swing.JLabel lblnombre4;
    private javax.swing.JLabel lblnombre5;
    private javax.swing.JLabel lblnombre6;
    private javax.swing.JLabel lblnombre7;
    private javax.swing.JLabel lblpass;
    private javax.swing.JLabel lblpass1;
    private javax.swing.JLabel lblrango;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtrecuperar;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
