/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Vista.*;
import Controlador.conexiones;
import Metodos.MetodoSQLVehiculos;
import Metodos.metodosSQLPersonas;
import Modelo.Persona;
import Modelo.Persona;
import Modelo.Usuario;
import Modelo.Vehiculos;
import Vista.BuscarVehiculo;
import Vista.BuscarVehiculo;
import Vista.MenuPrincipal;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class RegistroVehiculos extends javax.swing.JFrame {

    /**
     * Creates new form RegistroPersonas
     */
    conexiones con = new conexiones();
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelo;
    int ng;
    String tip;

    public void setNg(int ng) {
        this.ng = ng;
    }

    public RegistroVehiculos() {
        initComponents();
        listar();
        setIconImage(getIconImage());
        this.setLocationRelativeTo(null);

//        listar();
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Images/autoicon.jpg"));

        return retValue;
    }
    MetodoSQLVehiculos sql = new MetodoSQLVehiculos();

    void limpiartabla() {
        int filas = jVehiculos.getRowCount();
        for (int i = 0; i < filas; i++) {
            modelo.removeRow(0);

        }
    }

    //METODO LISTAR
    void listar() {
        String sql = "SELECT * FROM vehiculos";
        try {
            cn = con.Conectarse();
            st = cn.createStatement();
            rs = st.executeQuery(sql);
            Object[] veh = new Object[6];
            modelo = (DefaultTableModel) jVehiculos.getModel();
            while (rs.next()) {
                veh[0] = rs.getString("numplaca");
                veh[1] = rs.getString("tipo");
                veh[2] = rs.getString("marca");
                veh[3] = rs.getString("modelo");
                veh[4] = rs.getDate("matricula");
                veh[5] = rs.getString("color");
                modelo.addRow(veh);

            }
            jVehiculos.setModel(modelo);
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        panelbotones = new javax.swing.JPanel();
        btnregistrar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnconsultar1 = new javax.swing.JButton();
        IngresoDatospanel = new javax.swing.JPanel();
        lblcodigo = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        lblcodigo1 = new javax.swing.JLabel();
        lblcodigo2 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        lblcodigo3 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        lblcodigo4 = new javax.swing.JLabel();
        lblcodigo5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnlimpiar = new javax.swing.JButton();
        combocarro = new javax.swing.JComboBox<>();
        txtColor = new javax.swing.JTextField();
        Date = new com.toedter.calendar.JDateChooser();
        lblminimizar = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        tablap = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jVehiculos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(111, 174, 2), 5, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelbotones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bradley Hand ITC", 1, 14), new java.awt.Color(111, 174, 2))); // NOI18N
        panelbotones.setOpaque(false);

        btnregistrar.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        btnregistrar.setForeground(new java.awt.Color(111, 174, 2));
        btnregistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nuevo_doc.png"))); // NOI18N
        btnregistrar.setText("INGRESAR");
        btnregistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnregistrar.setContentAreaFilled(false);
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });

        btneliminar.setBackground(new java.awt.Color(255, 255, 255));
        btneliminar.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        btneliminar.setForeground(new java.awt.Color(111, 174, 2));
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eliminar_doc.png"))); // NOI18N
        btneliminar.setText("ELIMINAR");
        btneliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btneliminar.setContentAreaFilled(false);
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(111, 174, 2));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/guardar_doc.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(111, 174, 2));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Home_32px.png"))); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.setContentAreaFilled(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnconsultar1.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        btnconsultar1.setForeground(new java.awt.Color(111, 174, 2));
        btnconsultar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buscar_doc.png"))); // NOI18N
        btnconsultar1.setText("BUSCAR");
        btnconsultar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnconsultar1.setContentAreaFilled(false);
        btnconsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelbotonesLayout = new javax.swing.GroupLayout(panelbotones);
        panelbotones.setLayout(panelbotonesLayout);
        panelbotonesLayout.setHorizontalGroup(
            panelbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelbotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelbotonesLayout.createSequentialGroup()
                        .addComponent(btnregistrar)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(panelbotonesLayout.createSequentialGroup()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnconsultar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(11, 11, 11))))
            .addGroup(panelbotonesLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelbotonesLayout.setVerticalGroup(
            panelbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelbotonesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnregistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnconsultar1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel1.add(panelbotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 280, 210));

        IngresoDatospanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INGRESO DATOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18), new java.awt.Color(111, 174, 2))); // NOI18N
        IngresoDatospanel.setOpaque(false);

        lblcodigo.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblcodigo.setForeground(new java.awt.Color(111, 174, 2));
        lblcodigo.setText("PLaca");

        txtPlaca.setBackground(new java.awt.Color(51, 51, 51));
        txtPlaca.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtPlaca.setForeground(new java.awt.Color(111, 174, 2));
        txtPlaca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        txtPlaca.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });

        lblcodigo1.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblcodigo1.setForeground(new java.awt.Color(111, 174, 2));
        lblcodigo1.setText("Tipo");

        lblcodigo2.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblcodigo2.setForeground(new java.awt.Color(111, 174, 2));
        lblcodigo2.setText("Marca:");

        txtMarca.setBackground(new java.awt.Color(51, 51, 51));
        txtMarca.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtMarca.setForeground(new java.awt.Color(111, 174, 2));
        txtMarca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        txtMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMarcaKeyReleased(evt);
            }
        });

        lblcodigo3.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblcodigo3.setForeground(new java.awt.Color(111, 174, 2));
        lblcodigo3.setText("Modelo:");

        txtModelo.setBackground(new java.awt.Color(51, 51, 51));
        txtModelo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtModelo.setForeground(new java.awt.Color(111, 174, 2));
        txtModelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        txtModelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtModeloKeyReleased(evt);
            }
        });

        lblcodigo4.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblcodigo4.setForeground(new java.awt.Color(111, 174, 2));
        lblcodigo4.setText("Color:");

        lblcodigo5.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        lblcodigo5.setForeground(new java.awt.Color(111, 174, 2));
        lblcodigo5.setText("Matricula:");

        jLabel4.setForeground(new java.awt.Color(111, 174, 2));
        jLabel4.setText("*");

        btnlimpiar.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        btnlimpiar.setForeground(new java.awt.Color(111, 174, 2));
        btnlimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/borrar.png"))); // NOI18N
        btnlimpiar.setText("LIMPIAR");
        btnlimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnlimpiar.setContentAreaFilled(false);
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        combocarro.setBackground(new java.awt.Color(51, 51, 51));
        combocarro.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        combocarro.setForeground(new java.awt.Color(111, 174, 2));
        combocarro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "CARRO", "MOTO", "CAMION" }));
        combocarro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        combocarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combocarroActionPerformed(evt);
            }
        });

        txtColor.setBackground(new java.awt.Color(51, 51, 51));
        txtColor.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtColor.setForeground(new java.awt.Color(111, 174, 2));
        txtColor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(111, 174, 2)));
        txtColor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtColorKeyReleased(evt);
            }
        });

        Date.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout IngresoDatospanelLayout = new javax.swing.GroupLayout(IngresoDatospanel);
        IngresoDatospanel.setLayout(IngresoDatospanelLayout);
        IngresoDatospanelLayout.setHorizontalGroup(
            IngresoDatospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IngresoDatospanelLayout.createSequentialGroup()
                .addGroup(IngresoDatospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IngresoDatospanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(IngresoDatospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblcodigo5)
                            .addComponent(lblcodigo2)
                            .addGroup(IngresoDatospanelLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(IngresoDatospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(combocarro, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(IngresoDatospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblcodigo)
                                        .addGroup(IngresoDatospanelLayout.createSequentialGroup()
                                            .addGap(48, 48, 48)
                                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(IngresoDatospanelLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btnlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(IngresoDatospanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IngresoDatospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcodigo4)
                    .addGroup(IngresoDatospanelLayout.createSequentialGroup()
                        .addComponent(lblcodigo3)
                        .addGap(304, 304, 304)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblcodigo1))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        IngresoDatospanelLayout.setVerticalGroup(
            IngresoDatospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IngresoDatospanelLayout.createSequentialGroup()
                .addComponent(lblcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lblcodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(combocarro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblcodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(IngresoDatospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcodigo3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblcodigo5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblcodigo4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jPanel1.add(IngresoDatospanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 340, 520));

        lblminimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Expand_Arrow_32px.png"))); // NOI18N
        lblminimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblminimizarMouseClicked(evt);
            }
        });
        jPanel1.add(lblminimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 10, 40, 30));

        btnCerrar.setBackground(new java.awt.Color(0, 0, 0));
        btnCerrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Delete_32px.png"))); // NOI18N
        btnCerrar.setAutoscrolls(true);
        btnCerrar.setBorder(null);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCerrar.setOpaque(true);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, -1, -1));

        tablap.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTROS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18), new java.awt.Color(111, 174, 2))); // NOI18N
        tablap.setOpaque(false);

        jVehiculos.setBackground(new java.awt.Color(111, 174, 2));
        jVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PLACA", "Tipo", "Marca", "Modelo", "Matricula", "Color"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jVehiculos.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jVehiculosAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jVehiculosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jVehiculos);

        javax.swing.GroupLayout tablapLayout = new javax.swing.GroupLayout(tablap);
        tablap.setLayout(tablapLayout);
        tablapLayout.setHorizontalGroup(
            tablapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addContainerGap())
        );
        tablapLayout.setVerticalGroup(
            tablapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(tablap, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 560, 460));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/registros.gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    public void Clear() {

        txtColor.setText("");
        txtMarca.setText("");
        txtPlaca.setText("");
        Date.setDate(null);
        combocarro.setSelectedItem("Seleccione");
        txtModelo.setText("");

    }

    public boolean ValidaPlaca(String placa) {
        // Patron para validar el email
        Pattern pattern = Pattern.compile("^[_A-Za-z]*-[0-9]");
        Matcher mather = pattern.matcher(placa);
        return mather.find();
    }
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        int s = JOptionPane.showConfirmDialog(null, "Esta seguro de modificar este registro", "Si/No", 0);
        if (s == 0) {
            boolean estado = false;
            if (txtPlaca.getText().isEmpty() || txtMarca.getText().isEmpty() || txtModelo.getText().isEmpty() || txtColor.getText().isEmpty()) {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "*CAMPOS OBLIGATORIOS");
//             CARRO, MOTO, CAMION
            } else {

                java.sql.Date fecha = null;
                Date dia = Date.getDate();
                if (dia != null) {
                    long d = dia.getTime();
                    fecha = new java.sql.Date(d);

                } else {
                    Date dates = new Date();
                    DateFormat formato = new SimpleDateFormat("dd-MM-yyyy");
                    formato.format(dates);
                    Date.setDate(dates);
                    long d = dia.getTime();
                    fecha = new java.sql.Date(d);
                }
//              String placa, String tipo, String marca, String modelo, Date matricula, String color

                int i = sql.actualizar(txtPlaca.getText(), (String) combocarro.getSelectedItem(), txtMarca.getText(), txtModelo.getText(), fecha, txtColor.getText());

                if (i > 0) {
                    Toolkit.getDefaultToolkit().beep();

                    limpiartabla();
                    listar();
                    Clear();

                } else {
                    Toolkit.getDefaultToolkit().beep();

                    txtPlaca.setText("");

                }
                txtPlaca.setEditable(true);
                txtPlaca.setEnabled(true);
            }
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        int s = JOptionPane.showConfirmDialog(null, "Desea eliminar  este vehiculo", "Si/No", 0);
        if (s == 0) {
            int res = 0;
            int row = jVehiculos.getSelectedRow();
            int fila = jVehiculos.getSelectedColumnCount();
            if (fila < 1) {
                JOptionPane.showMessageDialog(null, "DEBE SELECCIONAR UN REGISTRO DE LA TABLA", "AVISO", JOptionPane.INFORMATION_MESSAGE);

            } else {
                res = sql.eliminarRegistro(jVehiculos.getValueAt(row, 0).toString());
                if (res >= 0) {
                    limpiartabla();
                    listar();
                    Clear();
                }
            }
            txtPlaca.setEditable(true);
            txtPlaca.setEnabled(true);

        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
        int s = JOptionPane.showConfirmDialog(null, "Desea registrar este vehiculo", "Si/No", 0);
        if (s == 0) {
            txtPlaca.setEditable(true);
            txtPlaca.setEnabled(true);
            boolean estado = false;
            if (txtPlaca.getText().isEmpty() || txtMarca.getText().isEmpty() || txtModelo.getText().isEmpty() || txtColor.getText().isEmpty()) {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(this, "*CAMPOS OBLIGATORIOS");
//             CARRO, MOTO, CAMION
            } else {
                if (ValidaPlaca(txtPlaca.getText()) == true) {
                    estado = true;
                    java.sql.Date fecha = null;
                    Date dia = Date.getDate();
                    if (dia != null) {
                        long d = dia.getTime();
                        fecha = new java.sql.Date(d);

                    } else {
                        Date dates = new Date();
                        DateFormat formato = new SimpleDateFormat("dd-MM-yyyy");
                        formato.format(dates);
                        Date.setDate(dates);
                        long d = dia.getTime();
                        fecha = new java.sql.Date(d);
                    }
//              String placa, String tipo, String marca, String modelo, Date matricula, String color

                    Vehiculos vehi = new Vehiculos(txtPlaca.getText(), (String) combocarro.getSelectedItem(), txtMarca.getText(), txtModelo.getText(), fecha, txtColor.getText(), estado);
                    int i = sql.guardar(vehi);

                    if (i > 0) {
                        Toolkit.getDefaultToolkit().beep();
                        JOptionPane.showMessageDialog(this, "Vehiculo registrado con exito");
                        limpiartabla();
                        listar();
                        Clear();
                    } else {
                        Toolkit.getDefaultToolkit().beep();
                        JOptionPane.showMessageDialog(this, "NO REGISTRADO, YA EXISTE LA PLACA");
                        txtPlaca.setText("");

                    }
                } else {
                    JOptionPane.showMessageDialog(this, "PLACA INVALIDA", "ERROR", JOptionPane.ERROR_MESSAGE);
                    txtPlaca.setText("");
                }

            }
        }
    }//GEN-LAST:event_btnregistrarActionPerformed

    private void btnconsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultar1ActionPerformed
        BuscarVehiculo b = new BuscarVehiculo(this, true);
        b.setVisible(true);
        txtPlaca.setText(b.getPlaca());
        combocarro.setSelectedItem(b.getTip());
        txtMarca.setText(b.getMarca());
        txtModelo.setText(b.getModelo());
        txtColor.setText(b.getColor());
        Date.setDate(b.fecha);
        txtPlaca.setEditable(true);
        txtPlaca.setEnabled(false);

    }//GEN-LAST:event_btnconsultar1ActionPerformed

    private void lblminimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblminimizarMouseClicked

    }//GEN-LAST:event_lblminimizarMouseClicked

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();

    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        txtPlaca.setEditable(true);
        txtPlaca.setEnabled(true);
        Clear();
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void txtMarcaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMarcaKeyReleased
        Character validar = evt.getKeyChar();
        //NO TENGAN LETRAS
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "¡Ingrese solo letras!", "MENSAJE DE ERROR", JOptionPane.ERROR_MESSAGE);
            txtMarca.setText("");
        }

    }//GEN-LAST:event_txtMarcaKeyReleased

    private void txtModeloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModeloKeyReleased
        //VALIDACIONES

    }//GEN-LAST:event_txtModeloKeyReleased

    private void combocarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combocarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combocarroActionPerformed

    private void txtColorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColorKeyReleased
        Character validar = evt.getKeyChar();
        //NO TENGAN LETRAS
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "¡Ingrese solo letras!", "MENSAJE DE ERROR", JOptionPane.ERROR_MESSAGE);
            txtColor.setText("");
        }
    }//GEN-LAST:event_txtColorKeyReleased

    private void jVehiculosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jVehiculosAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jVehiculosAncestorAdded

    private void jVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jVehiculosMouseClicked
        txtPlaca.setEditable(false);
        txtPlaca.setEnabled(false);
        int fila = jVehiculos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Vehiuclo no seleccionada");
        } else {

            txtPlaca.setText(jVehiculos.getValueAt(fila, 0).toString());
            combocarro.setSelectedItem(jVehiculos.getValueAt(fila, 1).toString());
            txtMarca.setText(jVehiculos.getValueAt(fila, 2).toString());
            txtModelo.setText(jVehiculos.getValueAt(fila, 3).toString());

            txtColor.setText(jVehiculos.getValueAt(fila, 5).toString());
//            java.sql.Date fecha = (java.sql.Date) jVehiculos.getValueAt(fila, 4);
            String fechas = jVehiculos.getValueAt(fila, 4).toString();
            Date dat;
            try {
                dat = new SimpleDateFormat("yyyy-MM-dd").parse(fechas);
                Date.setDate(dat);
            } catch (ParseException e) {
                System.out.println("Eror en fecha de ingreso");
            }

        }

    }//GEN-LAST:event_jVehiculosMouseClicked

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Date;
    private javax.swing.JPanel IngresoDatospanel;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnconsultar1;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnregistrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> combocarro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jVehiculos;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JLabel lblcodigo1;
    private javax.swing.JLabel lblcodigo2;
    private javax.swing.JLabel lblcodigo3;
    private javax.swing.JLabel lblcodigo4;
    private javax.swing.JLabel lblcodigo5;
    private javax.swing.JLabel lblminimizar;
    private javax.swing.JPanel panelbotones;
    private javax.swing.JPanel tablap;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
